# Bluesky Ranker — Example Notebook

This notebook demonstrates the typical workflow:
- Fetch recent public posts into SQLite (upsert-by-URI)
- Load posts from SQLite into a Polars DataFrame
- Rank posts using the TopicRanker (TF–IDF/Count/SBERT)
- Inspect the top clusters and sample posts
- (Optional) Generate a per-handle cluster report to Markdown

> Note: This notebook expects a SQLite DB with posts.
Create one via the sample (no network): `python -m blueskyranker.sample_db --db newsflows_sample.db`
or fetch live data via the fetcher CLI.

In [1]:
# Imports and setup
import polars as pl
from blueskyranker.fetcher import Fetcher, ensure_db, load_posts_df
from blueskyranker.ranker import TopicRanker

In [3]:
from blueskyranker.pipeline import run_fetch_rank_push

run_fetch_rank_push(
    handles=['news-flows-nl.bsky.social'],
    method='networkclustering-tfidf',
    cluster_window_days=1,
    engagement_window_days=1,
    push_window_days=1,
    fetch_max_age_days=1,
    actor_diversity=True,
    annotator_batch_size=10,
    annotator_timeout = 60,
    annotator_lookback_hours=24,
    dry_run=True,
    dry_run_verbose=True,
    enricher_center_parties=True,
    enricher_politicians_data_path='/home/eklk/data/storage100gb5/blueskyranker/blueskyranker/politicians_nl.csv',
    enricher_use_wikidata=True,
)

Posts fetched (all handles): 0post [00:00, ?post/s]
Posts fetched (all handles): 100post [00:44,  2.24post/s]
Posts fetched (all handles): 200post [01:33,  1.40post/s]
Posts fetched (all handles): 300post [02:25,  2.43post/s]
Posts fetched (all handles): 400post [03:08,  2.17post/s]
Posts fetched (all handles): 479post [03:43,  2.50post/s]



Handles: 100%|██████████| 1/1 [03:44<00:00, 224.72s/handle]
Posts fetched (all handles): 479post [03:44,  2.13post/s]

✅ DONE news-flows-nl.bsky.social: upserted 479 posts into SQLite

============================================================
STARTING BATCH PROCESSING
============================================================
Total articles: 1136
Batch size: 10
Total batches: 114
Starting from batch: 1
Batches to process: 114
Run directory: actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111
============================================================


--- Batch 1/114 (10 articles) ---
Memory: 1010.84 MB
✓ Batch completed in 72.8s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0000.parquet

--- Batch 2/114 (10 articles) ---
Memory: 1017.45 MB
✓ Batch completed in 123.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0001.parquet

--- Batch 3/114 (10 articles) ---
Memory: 1017.97 MB
✓ Batch completed in 112.3s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0002.parquet

--- Batch 4/114 (10 articles) ---
Memory: 1017.97 MB
✓ Batch completed in 201.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0003.parquet

--- Batch 5/114 (10 articles) ---
Memory: 1017.97 MB
✓ Batch completed in 210.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0004.parquet

--- Batch 6/114 (10 articles) ---
Memory: 1017.97 MB
✓ Batch completed in 146.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0005.parquet

--- Batch 7/114 (10 articles) ---
Memory: 1017.97 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 308.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0006.parquet

--- Batch 8/114 (10 articles) ---
Memory: 1017.97 MB
Request timed out after 60s - restarting client
Ollama client recreated
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 251.8s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0007.parquet

--- Batch 9/114 (10 articles) ---
Memory: 1020.04 MB
✓ Batch completed in 179.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0008.parquet

--- Batch 10/114 (10 articles) ---
Memory: 1020.04 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 269.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0009.parquet

--- Batch 11/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 127.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0010.parquet

--- Batch 12/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 109.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0011.parquet

--- Batch 13/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 92.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0012.parquet

--- Batch 14/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 141.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0013.parquet

--- Batch 15/114 (10 articles) ---
Memory: 1020.26 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 196.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0014.parquet

--- Batch 16/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 76.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0015.parquet

--- Batch 17/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 81.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0016.parquet

--- Batch 18/114 (10 articles) ---
Memory: 1020.26 MB
✓ Batch completed in 96.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0017.parquet

--- Batch 19/114 (10 articles) ---
Memory: 1020.77 MB
✓ Batch completed in 176.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0018.parquet

--- Batch 20/114 (10 articles) ---
Memory: 1020.77 MB
✓ Batch completed in 201.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0019.parquet

--- Batch 21/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 264.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0020.parquet

--- Batch 22/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 216.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0021.parquet

--- Batch 23/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 305.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0022.parquet

--- Batch 24/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 197.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0023.parquet

--- Batch 25/114 (10 articles) ---
Memory: 1020.77 MB
✓ Batch completed in 116.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0024.parquet

--- Batch 26/114 (10 articles) ---
Memory: 1020.77 MB
✓ Batch completed in 126.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0025.parquet

--- Batch 27/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 320.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0026.parquet

--- Batch 28/114 (10 articles) ---
Memory: 1020.77 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 218.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0027.parquet

--- Batch 29/114 (10 articles) ---
Memory: 1020.77 MB
✓ Batch completed in 193.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0028.parquet

--- Batch 30/114 (10 articles) ---
Memory: 1021.25 MB
✓ Batch completed in 120.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0029.parquet

--- Batch 31/114 (10 articles) ---
Memory: 1021.47 MB
✓ Batch completed in 85.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0030.parquet

--- Batch 32/114 (10 articles) ---
Memory: 1021.47 MB
✓ Batch completed in 136.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0031.parquet

--- Batch 33/114 (10 articles) ---
Memory: 1021.47 MB
✓ Batch completed in 140.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0032.parquet

--- Batch 34/114 (10 articles) ---
Memory: 1021.47 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 180.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0033.parquet

--- Batch 35/114 (10 articles) ---
Memory: 1021.47 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 194.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0034.parquet

--- Batch 36/114 (10 articles) ---
Memory: 1021.47 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 323.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0035.parquet

--- Batch 37/114 (10 articles) ---
Memory: 1021.47 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 213.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0036.parquet

--- Batch 38/114 (10 articles) ---
Memory: 1021.72 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 272.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0037.parquet

--- Batch 39/114 (10 articles) ---
Memory: 1021.72 MB
✓ Batch completed in 134.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0038.parquet

--- Batch 40/114 (10 articles) ---
Memory: 1022.11 MB
✓ Batch completed in 149.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0039.parquet

--- Batch 41/114 (10 articles) ---
Memory: 1022.33 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 191.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0040.parquet

--- Batch 42/114 (10 articles) ---
Memory: 1022.33 MB
✓ Batch completed in 205.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0041.parquet

--- Batch 43/114 (10 articles) ---
Memory: 1022.33 MB
✓ Batch completed in 106.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0042.parquet

--- Batch 44/114 (10 articles) ---
Memory: 1022.33 MB
✓ Batch completed in 106.3s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0043.parquet

--- Batch 45/114 (10 articles) ---
Memory: 1022.56 MB
✓ Batch completed in 108.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0044.parquet

--- Batch 46/114 (10 articles) ---
Memory: 1022.56 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 166.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0045.parquet

--- Batch 47/114 (10 articles) ---
Memory: 1022.56 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 232.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0046.parquet

--- Batch 48/114 (10 articles) ---
Memory: 1022.56 MB
✓ Batch completed in 132.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0047.parquet

--- Batch 49/114 (10 articles) ---
Memory: 1022.56 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 179.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0048.parquet

--- Batch 50/114 (10 articles) ---
Memory: 1022.87 MB
✓ Batch completed in 89.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0049.parquet

--- Batch 51/114 (10 articles) ---
Memory: 1022.87 MB
✓ Batch completed in 127.8s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0050.parquet

--- Batch 52/114 (10 articles) ---
Memory: 1022.87 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 324.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0051.parquet

--- Batch 53/114 (10 articles) ---
Memory: 1023.09 MB
✓ Batch completed in 145.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0052.parquet

--- Batch 54/114 (10 articles) ---
Memory: 1023.09 MB
Request timed out after 60s - restarting client
Ollama client recreated
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 263.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0053.parquet

--- Batch 55/114 (10 articles) ---
Memory: 1023.54 MB
✓ Batch completed in 101.4s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0054.parquet

--- Batch 56/114 (10 articles) ---
Memory: 1023.54 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 227.3s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0055.parquet

--- Batch 57/114 (10 articles) ---
Memory: 1023.54 MB
✓ Batch completed in 163.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0056.parquet

--- Batch 58/114 (10 articles) ---
Memory: 1023.54 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 216.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0057.parquet

--- Batch 59/114 (10 articles) ---
Memory: 1023.54 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 370.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0058.parquet

--- Batch 60/114 (10 articles) ---
Memory: 1023.76 MB
✓ Batch completed in 166.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0059.parquet

--- Batch 61/114 (10 articles) ---
Memory: 1023.76 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 165.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0060.parquet

--- Batch 62/114 (10 articles) ---
Memory: 1023.76 MB
✓ Batch completed in 150.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0061.parquet

--- Batch 63/114 (10 articles) ---
Memory: 1023.98 MB
✓ Batch completed in 93.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0062.parquet

--- Batch 64/114 (10 articles) ---
Memory: 1023.98 MB
✓ Batch completed in 101.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0063.parquet

--- Batch 65/114 (10 articles) ---
Memory: 1023.98 MB
✓ Batch completed in 123.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0064.parquet

--- Batch 66/114 (10 articles) ---
Memory: 1023.98 MB
✓ Batch completed in 86.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0065.parquet

--- Batch 67/114 (10 articles) ---
Memory: 1023.98 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 163.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0066.parquet

--- Batch 68/114 (10 articles) ---
Memory: 1023.98 MB
✓ Batch completed in 137.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0067.parquet

--- Batch 69/114 (10 articles) ---
Memory: 1024.23 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 218.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0068.parquet

--- Batch 70/114 (10 articles) ---
Memory: 1024.23 MB
✓ Batch completed in 153.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0069.parquet

--- Batch 71/114 (10 articles) ---
Memory: 1024.23 MB
✓ Batch completed in 133.5s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0070.parquet

--- Batch 72/114 (10 articles) ---
Memory: 1024.23 MB
✓ Batch completed in 128.2s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0071.parquet

--- Batch 73/114 (10 articles) ---
Memory: 1024.23 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 223.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0072.parquet

--- Batch 74/114 (10 articles) ---
Memory: 1024.23 MB
✓ Batch completed in 158.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0073.parquet

--- Batch 75/114 (10 articles) ---
Memory: 1024.23 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 226.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0074.parquet

--- Batch 76/114 (10 articles) ---
Memory: 1024.23 MB
✓ Batch completed in 160.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0075.parquet

--- Batch 77/114 (10 articles) ---
Memory: 1024.23 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 143.9s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0076.parquet

--- Batch 78/114 (10 articles) ---
Memory: 1024.23 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 183.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0077.parquet

--- Batch 79/114 (10 articles) ---
Memory: 1024.46 MB
✓ Batch completed in 124.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0078.parquet

--- Batch 80/114 (10 articles) ---
Memory: 1024.46 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 274.1s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0079.parquet

--- Batch 81/114 (10 articles) ---
Memory: 1024.46 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 204.8s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0080.parquet

--- Batch 82/114 (10 articles) ---
Memory: 1024.70 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 136.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0081.parquet

--- Batch 83/114 (10 articles) ---
Memory: 1024.70 MB
✓ Batch completed in 116.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0082.parquet

--- Batch 84/114 (10 articles) ---
Memory: 1024.70 MB
✓ Batch completed in 144.8s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0083.parquet

--- Batch 85/114 (10 articles) ---
Memory: 1024.70 MB
✓ Batch completed in 114.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0084.parquet

--- Batch 86/114 (10 articles) ---
Memory: 1024.70 MB
Request timed out after 60s - restarting client
Ollama client recreated
Retry after timeout also failed: timed out
✓ Batch completed in 266.6s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0085.parquet

--- Batch 87/114 (10 articles) ---
Memory: 1024.92 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 276.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0086.parquet

--- Batch 88/114 (10 articles) ---
Memory: 1024.92 MB
✓ Batch completed in 219.0s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0087.parquet

--- Batch 89/114 (10 articles) ---
Memory: 1024.92 MB
✓ Batch completed in 122.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0088.parquet

--- Batch 90/114 (10 articles) ---
Memory: 1024.92 MB
Request timed out after 60s - restarting client
Ollama client recreated
✓ Batch completed in 190.7s — saved to actor_annotation_batches/news-flows-nl_bsky_social_20260317T152111/batch_0089.parquet

--- Batch 91/114 (10 articles) ---
Memory: 1024.92 MB

Extracting names: 100%|██████████| 1468/1468 [00:12<00:00, 121.92it/s]

Step 3.3: Exact matching on core_actor_name...
  → Matched 85 actors with exact core_actor_name match
Step 3.4: Token matching on core_actor_name...
→ Matched 42 actors with token match on core_actor_name
These names are matched with reference data: [{'core_actor_name': 'Rob Jetten', 'matched_name': 'ROB JETTEN'}, {'core_actor_name': 'Jetten', 'matched_name': 'ROB JETTEN'}, {'core_actor_name': 'Van Den Brink', 'matched_name': 'BART VAN DEN BRINK'}, {'core_actor_name': 'Thierry Aartsen', 'matched_name': 'THIERRY AARTSEN'}, {'core_actor_name': 'Inge Van Dijk', 'matched_name': 'INGE VAN DIJK'}, {'core_actor_name': None, 'matched_name': 'ChristenUnie'}, {'core_actor_name': 'Heinen', 'matched_name': 'EELCO HEINEN'}, {'core_actor_name': 'Eelco Heinen', 'matched_name': 'EELCO HEINEN'}, {'core_actor_name': 'Mona Keijzer', 'matched_name': 'MONA KEIJZER'}, {'core_actor_name': 'Mirjam Bikker', 'matched_name': 'MIRJAM BIKKER'}, {'core_actor_name': 'Lisa Westerveld', 'matched_name': 'LISA WESTERVELD'}, {'core_actor_name': 'Diederik Van Dijk', 'matched_name': 'DIEDERIK VAN DIJK'}, {'core_actor_name': 'Marijke Synhaeve', 'matched_name': 'MARIJKE SYNHAEVE'}, {'core_actor_name': 'Hermans', 'matched_name': 'SOPHIE HERMANS'}, {'core_actor_name': 'Shirin Musa', 'matched_name': 'SHIRIN MUSA'}, {'core_actor_name': 'Pepijn Van Houwelingen', 'matched_name': 'PEPIJN VAN HOUWELINGEN'}, {'core_actor_name': 'David Van Weel', 'matched_name': 'DAVID VAN WEEL'}, {'core_actor_name': 'Van Weel', 'matched_name': 'DAVID VAN WEEL'}, {'core_actor_name': 'Van Justitie David Van Weel', 'matched_name': 'DAVID VAN WEEL'}, {'core_actor_name': 'Jean Rummenie', 'matched_name': 'JEAN RUMMENIE'}, {'core_actor_name': 'Annabel Nanninga', 'matched_name': 'ANNABEL NANNINGA'}, {'core_actor_name': 'Joost Eerdmans', 'matched_name': 'JOOST EERDMANS'}, {'core_actor_name': 'Geert Wilders', 'matched_name': 'GEERT WILDERS'}, {'core_actor_name': 'Hidde Heutink', 'matched_name': 'HIDDE HEUTINK'}, {'core_actor_name': 'Aartsen', 'matched_name': 'THIERRY AARTSEN'}, {'core_actor_name': 'Van Financiën Eelco Heinen', 'matched_name': 'EELCO HEINEN'}, {'core_actor_name': 'Sophie Hermans', 'matched_name': 'SOPHIE HERMANS'}, {'core_actor_name': 'Ergin', 'matched_name': 'DOĞUKAN ERGIN'}, {'core_actor_name': 'Dijk', 'matched_name': 'HEERA DIJK'}, {'core_actor_name': 'Keijzer', 'matched_name': 'MONA KEIJZER'}, {'core_actor_name': 'Cornelis Van Der Werf', 'matched_name': 'HANNEKE VAN DER WERF'}, {'core_actor_name': 'Karremans', 'matched_name': 'VINCENT KARREMANS'}, {'core_actor_name': 'Lidewij De Vos', 'matched_name': 'LIDEWIJ DE VOS'}, {'core_actor_name': 'Ruben Brekelmans', 'matched_name': 'RUBEN BREKELMANS'}, {'core_actor_name': 'Wieke Paulusma', 'matched_name': 'WIEKE PAULUSMA'}, {'core_actor_name': 'Jesse Klaver', 'matched_name': 'JESSE KLAVER'}, {'core_actor_name': 'Ulysse Ellian', 'matched_name': 'ULYSSE ELLIAN'}, {'core_actor_name': 'André Flach', 'matched_name': 'ANDRÉ FLACH'}, {'core_actor_name': 'Kamerlid Lammers', 'matched_name': 'ANNELOTTE LAMMERS'}, {'core_actor_name': 'Partijgenoot Ulysse Ellian', 'matched_name': 'ULYSSE ELLIAN'}, {'core_actor_name': 'Tijs Van Den Brink', 'matched_name': 'TIJS VAN DEN BRINK'}]
Step 3.5: Matching on original actor_name...
→ Matched 0 actors with actor_name matching

Total matched: 159 actors with reference data
Step 3.6: Querying Wikidata for 1341 actors with missing party info...
Querying 370 unique names...

Wikidata queries: 100%|██████████| 370/370 [07:47<00:00,  1.26s/it]

Updating party reference data with Wikidata results...
Writing updated politician reference data to /home/eklk/data/storage100gb5/blueskyranker/blueskyranker/politicians_nl_updated.csv...
Enriched 239 political actor records

Step 4: Calculating actors per party ideology...
Generated ideology statistics for 98 articles

============================================================
ENRICHMENT PIPELINE COMPLETED
============================================================


=== Dry Run: handle=news-flows-nl.bsky.social posts=231 method=networkclustering-tfidf threshold=0.2 windows=(cluster=1d, engagement=1d, push=1d)
  cluster=0 rank=1 size_push=8 engagement=6 keywords="luchtaanval ziekenhuis doden pakistaanse kabul afghanistan"
  cluster=71 rank=2 size_push=1 engagement=4 keywords="haar yvette broch keert terug franse"
  cluster=48 rank=3 size_push=2 engagement=3 keywords="oppaskinderen jaar peter nancy schröder duijn"
  cluster=30 rank=4 size_push=2 engagement=3 keywords="mensen libanon ruim vlucht voor door"
  cluster=60 rank=5 size_push=2 engagement=2 keywords="iran trump oorlog niet terrorismebestrijding veel"
  Top cluster posts (5 each):
    Cluster 0 — most recent posts (5):
      #1 | 2026-03-17T08:20:07.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhakdshhot2u | news=https://www.metronieuws.nl/in-het-nieuws/buitenland/2026/03/luchtaanval-treft-afghaans-ziekenhuis-kabul-br/ | text="Tientallen lichamen uit puin getroffen ziekenhuis Kabul gehaald   Reddingswerkers zoeken in de Afghaanse hoofdstad Kabul naar lichamen en overlevenden in het puin van een ziekenhu…" | title="Tientallen lichamen uit puin getroffen ziekenhuis Kabul gehaald" | desc="Reddingswerkers zoeken in puin van Afghaans ziekenhuis na Pakistaanse luchtaanval; minimaal 30 doden en vele gewonden."
      #2 | 2026-03-17T07:09:25.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhagnoxfjh2d | news=https://www.metronieuws.nl/in-het-nieuws/buitenland/2026/03/luchtaanval-ziekenhuis-kabul-honderden-doden-br/ | text="Afghanistan meldt 400 doden bij luchtaanval op ziekenhuis Kabul   Afghaanse autoriteiten stellen dat er zeker 400 mensen zijn omgekomen na een luchtaanval op een ziekenhuis in hoo…" | title="Afghanistan meldt 400 doden bij luchtaanval op ziekenhuis Kabul" | desc="Pakistaanse luchtaanval op Afghaans ziekenhuis doodt minstens 400 personen en verwondt 250 anderen, hoewel Pakistan het doelwit ontkent."
      #3 | 2026-03-17T06:50:29.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhafmbua7c2m | news=https://www.nu.nl/buitenland/6389463/tientallen-doden-in-afghaanse-afkickkliniek-door-pakistaanse-luchtaanval.html | text="Tientallen doden in Afghaanse afkickkliniek door Pakistaanse luchtaanval  Tientallen mensen in een Afghaanse afkickkliniek zijn maandagavond omgekomen bij een Pakistaanse luchtaan…" | title="Tientallen doden in Afghaanse afkickkliniek door Pakistaanse luchtaanval" | desc="Tientallen mensen in een Afghaanse afkickkliniek zijn maandagavond omgekomen bij een Pakistaanse luchtaanval. De Taliban stelt dat er bij de aanval 400 doden en 250 gewonden zijn …"
      #4 | 2026-03-17T04:00:00.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhaaf6i5jn24 | news=https://www.volkskrant.nl/buitenland/afghanistan-meldt-400-doden-bij-pakistaanse-luchtaanval-op-ziekenhuis-kaboel~bab3012f/ | text="Afghanistan meldt 400 doden bij Pakistaanse luchtaanval op ziekenhuis Kaboel   " | title="Afghanistan meldt 400 doden bij Pakistaanse luchtaanval op ziekenhuis Kaboel" | desc="De Afghaanse autoriteiten zeggen dat er zeker 400 mensen zijn omgekomen bij een Pakistaanse luchtaanval op een ziekenhuis in de hoofdstad Kaboel."
      #5 | 2026-03-17T03:54:04.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mha3pbgvhi22 | news=https://www.ad.nl/buitenland/afghanistan-meldt-400-doden-bij-pakistaanse-luchtaanval-op-ziekenhuis-kaboel~aab3012f/ | text="Afghanistan meldt 400 doden bij Pakistaanse luchtaanval op ziekenhuis Kaboel  De Afghaanse autoriteiten zeggen dat er zeker 400 mensen zijn omgekomen bij een Pakistaanse luchtaanv…" | title="Afghanistan meldt 400 doden bij Pakistaanse luchtaanval op ziekenhuis Kaboel" | desc="De Afghaanse autoriteiten zeggen dat er zeker 400 mensen zijn omgekomen bij een Pakistaanse luchtaanval op een ziekenhuis in de hoofdstad Kaboel."
    Cluster 71 — most recent posts (5):
      #1 | 2026-03-16T23:04:59.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mh7lndufrd2q | news=https://www.nu.nl/sport-overig/6389455/yvette-broch-35-keert-terug-uit-haar-pensioen-en-gaat-franse-club-brest-helpen.html | text="Yvette Broch (35) keert terug uit haar pensioen en gaat Franse club Brest helpen  Yvette Broch keert terug uit haar handbalpensioen. De 35-jarige oud-international maakt haar rent…" | title="Yvette Broch (35) keert terug uit haar pensioen en gaat Franse club Brest helpen" | desc="Yvette Broch keert terug uit haar handbalpensioen. De 35-jarige oud-international maakt haar rentree bij de Franse topclub Brest. Ze heeft daar een contract getekend tot het einde…"
    Cluster 48 — most recent posts (5):
      #1 | 2026-03-17T11:30:00.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhavb5card2q | news=https://www.geenstijl.nl/5188863/ziek/ | text="Peter Schröder en Nancy Duijn misbruikten zeer jonge oppaskinderen: 'Die van 1 jaar zijn het makkelijkst'  U leest het al: er is weer nieuws over die twee geesteszieke debielen di…" | title="GeenStijl: Peter Schröder en Nancy Duijn misbruikten zeer jonge oppaskinderen: 'Die van 1 jaar zijn het makkelijkst'" | desc=""_Gewoon luier uit en aan de gang_.""
      #2 | 2026-03-17T11:27:24.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhauw6guoo24 | news=https://www.rtl.nl/nieuws/binnenland/artikel/5579127/18-jaar-cel-en-tbs-geeist-voor-gruwelijk-seksueel-misbruik | text="18 jaar cel en tbs geëist voor 'gruwelijk' seksueel misbruik oppaskinderen  Het Openbaar Ministerie heeft in hoger beroep celstraffen van 18 jaar geëist en tbs met dwangverpleging…" | title="18 jaar cel en tbs geëist voor 'gruwelijk' seksueel misbruik oppaskinderen" | desc="Het Openbaar Ministerie heeft in hoger beroep celstraffen van 18 jaar geëist en tbs met dwangverpleging tegen Peter S. (62) en Nancy D. (57). Zij hebben bekend dat ze zeven oppask…"
    Cluster 30 — most recent posts (5):
      #1 | 2026-03-17T08:33:00.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhalrkqrdd2r | news=https://www.ad.nl/buitenland/live-midden-oosten-dode-in-abu-dhabi-door-brokstukken-raket-zorgen-over-800-000-mensen-die-in-libanon-op-straat-slapen~ac528ac3/ | text="Dode in Abu Dhabi door brokstukken raket, zorgen over 800.000 mensen die in Libanon op straat slapen  Het Rode Kruis waarschuwt voor aanhoudende regenbuien in Libanon. Meer dan 80…" | title="LIVE Midden-Oosten | Dode in Abu Dhabi door brokstukken raket, zorgen over 800.000 mensen die in Libanon op straat slapen" | desc="Het Rode Kruis waarschuwt voor aanhoudende regenbuien in Libanon. Meer dan 800.000 mensen zijn door Israëlische aanvallen op de vlucht geslagen. Velen daarvan slapen op straat. Ee…"
      #2 | 2026-03-16T21:28:35.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mh7gw6twzv2t | news=https://nos.nl/artikel/2606627-ruim-een-miljoen-libanezen-op-de-vlucht-vrees-voor-grote-humanitaire-ramp | text="Ruim een miljoen Libanezen op de vlucht; vrees voor grote humanitaire ramp  In Libanon zijn ruim een miljoen burgers op de vlucht geslagen voor Israëlische bombardementen, melden …" | title="Ruim een miljoen Libanezen op de vlucht; vrees voor grote humanitaire ramp" | desc="In totaal zijn er 886 Libanezen door de oorlog gedood, onder wie veel kinderen. Ruim 2000 mensen raakten gewond."
    Cluster 60 — most recent posts (5):
      #1 | 2026-03-17T14:41:00.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhbaanp6562m | news=https://www.ad.nl/buitenland/live-midden-oosten-hoofd-terrorismebestrijding-van-trump-stapt-op-ik-kan-de-oorlog-in-iran-met-mijn-geweten-niet-blijven-steunen~ac528ac3/ | text="Hoofd terrorismebestrijding van Trump stapt op: ‘Ik kan de oorlog in Iran met mijn geweten niet blijven steunen’  De hoogste verantwoordelijke voor terrorismebestrijding onder Don…" | title="LIVE Midden-Oosten | Hoofd terrorismebestrijding van Trump stapt op: ‘Ik kan de oorlog in Iran met mijn geweten niet blijven steunen’" | desc="De hoogste verantwoordelijke voor terrorismebestrijding onder Donald Trump is opgestapt vanwege de oorlog met Iran. Hij stelt dat Iran ‘geen onmiddellijke bedreiging’ vormde voor …"
      #2 | 2026-03-17T09:50:37.000000Z | post=at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhaqw3pwdl2r | news=https://www.nrc.nl/nieuws/2026/03/17/trump-kletst-tegen-elke-journalist-die-hem-belt-over-de-iran-oorlog-de-amerikaan-wordt-er-niet-veel-wijzer-van-a4923200 | text="Trump kletst tegen elke journalist die hem belt over de Iran-oorlog. De Amerikaan wordt er niet veel wijzer van  Sinds hij de oorlog in Iran begon, stond Donald Trump tientallen j…" | title="Trump kletst tegen elke journalist die hem belt over de Iran-oorlog. De Amerikaan wordt er niet veel wijzer van" | desc="Mediastrategie: Sinds hij de oorlog in Iran begon, stond Donald Trump tientallen journalisten ‘exclusief’ te woord via zijn mobiel. Veel nieuwswaardigs zegt de president in die ge…"
  Priority preview (top 15):
    1000  c=0     2026-03-17T08:20:07.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhakdshhot2u  | Tientallen lichamen uit puin getroffen ziekenhuis Kabul gehaald
    999  c=0     2026-03-17T07:09:25.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhagnoxfjh2d  | Afghanistan meldt 400 doden bij luchtaanval op ziekenhuis Kabul
    998  c=71    2026-03-16T23:04:59.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mh7lndufrd2q  | Yvette Broch (35) keert terug uit haar pensioen en gaat Franse club Brest helpen
    997  c=48    2026-03-17T11:30:00.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhavb5card2q  | GeenStijl: Peter Schröder en Nancy Duijn misbruikten zeer jonge oppaskinderen...
    996  c=48    2026-03-17T11:27:24.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhauw6guoo24  | 18 jaar cel en tbs geëist voor 'gruwelijk' seksueel misbruik oppaskinderen
    995  c=30    2026-03-17T08:33:00.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhalrkqrdd2r  | LIVE Midden-Oosten | Dode in Abu Dhabi door brokstukken raket, zorgen over 80...
    994  c=30    2026-03-16T21:28:35.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mh7gw6twzv2t  | Ruim een miljoen Libanezen op de vlucht; vrees voor grote humanitaire ramp
    993  c=60    2026-03-17T14:41:00.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhbaanp6562m  | LIVE Midden-Oosten | Hoofd terrorismebestrijding van Trump stapt op: ‘Ik kan ...
    992  c=60    2026-03-17T09:50:37.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhaqw3pwdl2r  | Trump kletst tegen elke journalist die hem belt over de Iran-oorlog. De Ameri...
    991  c=24    2026-03-17T08:36:49.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhalrui5wa2d  | Video | Dilan Yesilgöz stapt uit helikopter voor bezoek aan fregat Evertsen
    990  c=24    2026-03-17T06:37:10.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhafclzlnh2w  | Yeşilgöz bezoekt Nederlands marineschip: 'Zeer indrukwekkend'
    989  c=18    2026-03-17T12:33:00.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhb4isumxc22  | Belgische premier De Wever in de verdediging na suggestie weer Russisch gas t...
    988  c=18    2026-03-17T08:55:45.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhap2utfea2y  | Vredesbesprekingen tussen Oekraïne en Rusland doven uit door Amerikaanse focu...
    987  c=4     2026-03-17T10:45:27.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhasx6jart2q  | Trump is achter de schermen bezig met afzetten van Cubaanse president
    986  c=4     2026-03-17T09:41:04.000000Z  at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhb37yb3dx2n  | ‘Best grappig: doordat ik de havo niet heb gehaald, heb ik nu een baan waar i...
  JSON export: push_exports/push_news-flows-nl_bsky_social_2026-03-17T15-56-13 +0100.json

In [24]:
import polars as pl
from pathlib import Path
import pandas as pd 

# find the most recent parquet file that has enriched in it
batch_dir = Path('/home/eklk/data/storage100gb5/blueskyranker/actor_annotation_batches')
enriched_files = list(batch_dir.glob('*.parquet'))

# load the most recent one
if enriched_files:
    latest_file = max(enriched_files, key=lambda f: f.stat().st_mtime)
    print(f"Loading enriched data from {latest_file}")
    enriched_df = pl.read_parquet(latest_file)
enriched_df = pd.DataFrame(enriched_df, columns=enriched_df.columns)
print(enriched_df.shape)
enriched_df.head()

Loading enriched data from /home/eklk/data/storage100gb5/blueskyranker/actor_annotation_batches/news-flows-nl_bsky_social_enriched.parquet
(857, 10)

,uri,nr_actors_b,nr_actors_d,nr_actors_c,nr_actors_a,nr_actors_total,nr_actors_center,nr_actors_right,nr_actors_left,nr_actors_political
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1,0,0,0,1,NaN,NaN,NaN,NaN
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,1,0,3,4,NaN,NaN,NaN,NaN
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,0,1,7,8,3.0,3.0,1.0,7.0
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,3,1,1,7,12,NaN,NaN,NaN,NaN
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1,1,0,0,2,NaN,NaN,NaN,NaN

In [ ]:
enriched_df.nr_actors_political.value_counts(dropna=False)

nr_actors_political
NaN    759
1.0     60
2.0     22
3.0      6
4.0      6
5.0      3
7.0      1
Name: count, dtype: int64

In [26]:
enriched_df[enriched_df['uri'] == "at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhb4isumxc22"]

,uri,nr_actors_b,nr_actors_d,nr_actors_c,nr_actors_a,nr_actors_total,nr_actors_center,nr_actors_right,nr_actors_left,nr_actors_political
210,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,0,0,5,5,NaN,NaN,NaN,NaN

In [27]:
enriched_df[enriched_df['uri'] == "at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mhap2utfea2y"]

,uri,nr_actors_b,nr_actors_d,nr_actors_c,nr_actors_a,nr_actors_total,nr_actors_center,nr_actors_right,nr_actors_left,nr_actors_political
13,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,0,0,4,4,NaN,NaN,NaN,NaN

In [20]:
import pandas as pd 
enriched_df = pd.DataFrame(enriched_df, columns=enriched_df.columns)
print(enriched_df.shape)
enriched_df.head()

(345, 10)

,uri,nr_actors_b,nr_actors_c,nr_actors_a,nr_actors_d,nr_actors_total,nr_actors_right,nr_actors_center,nr_actors_left,nr_actors_political
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1,0,0,0,1,NaN,NaN,NaN,NaN
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,2,0,0,0,2,NaN,NaN,NaN,NaN
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,3,0,3,0,6,NaN,NaN,NaN,NaN
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,2,1,0,3,NaN,NaN,NaN,NaN
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1,0,0,0,1,NaN,NaN,NaN,NaN

In [24]:
enriched_df['nr_actors_total'] = enriched_df['nr_actors_total'].astype('Int64')  # Convert to nullable integer type
enriched_df.nr_actors_total.describe()

count       345.0
mean     2.837681
std      2.063604
min           1.0
25%           1.0
50%           2.0
75%           4.0
max          12.0
Name: nr_actors_total, dtype: Float64

In [18]:
enriched_df.isnull().sum()

uri                      0
nr_actors_b              0
nr_actors_c              0
nr_actors_a              0
nr_actors_d              0
nr_actors_total          0
nr_actors_right        308
nr_actors_center       308
nr_actors_left         308
nr_actors_political    308
dtype: int64

In [27]:
# Find the most recent run directory
batch_dir = Path('actor_annotation_batches')
run_dirs = sorted(batch_dir.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)
# remove if file name has enriched in it
run_dirs = [d for d in run_dirs if d.is_dir() and 'enriched' not in d.name]
latest_run = run_dirs[0]
print(f"Loading from: {latest_run}")

# Load all batches
files = sorted(latest_run.glob("batch_*.parquet"))
df = pl.concat([pl.read_parquet(f) for f in files])
print(f"{len(df)} rows, {len(files)} batch files")

df = pd.DataFrame(df, columns=df.columns)
df.head()

Loading from: actor_annotation_batches/news-flows-nl_bsky_social_20260310T084241
475 rows, 48 batch files

,uri,cid,author_handle,author_did,indexedAt,createdAt,text,reply_root_uri,reply_parent_uri,is_repost,...,reply_count,quote_count,news_title,news_description,news_uri,news_content,createdAt_ns,createdAt_dt,news_actors_raw,news_actors
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreidp4vlfrfojf33ep3ny5uvzwts45dumviwsvq7uf...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-03-09T09:09:19.254Z,2026-03-09T08:41:29.000000Z,In vlammen op: treinstation Glasgow voor een d...,NaN,NaN,0,...,0,0,In vlammen op: treinstation Glasgow voor een d...,In Glasgow is het centrale station gedeeltelij...,https://www.rtl.nl/nieuws/buitenland/video/d82...,Blijf op de hoogte van de nieuwste RTL program...,1773045689000000000,2026-03-09 08:41:29,"```json\n{\n ""actors"": []\n}\n```",None
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreifqranzlgikxbkjgv2u67dgwvsrhyqdtyrxqkpvn...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-03-09T10:13:09.753Z,2026-03-09T08:44:00.000000Z,"Twee baby's, heel uiteenlopend gewicht: 'Een m...",NaN,NaN,0,...,0,0,"Twee baby's, heel uiteenlopend gewicht: 'Een m...",Een vrouw in de VS is bevallen van een opvalle...,https://www.ad.nl/binnenland/twee-babys-heel-u...,Buitenlandredactie\n\nHet Cayuga Medical Cente...,1773045840000000000,2026-03-09 08:44:00,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Terrica"", ""actor_f..."
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreihwmg55iabpxyrd46fw45iqgfwrx3qq5q2q6dqwq...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-03-09T08:52:52.955Z,2026-03-09T08:49:43.000000Z,Max Verstappen doet definitief mee aan 24 uur ...,NaN,NaN,0,...,0,0,Max Verstappen doet definitief mee aan 24 uur ...,Max Verstappen doet definitief mee aan de 24 u...,https://www.nu.nl/formule-1/6388610/max-versta...,Max Verstappen doet definitief mee aan de 24 u...,1773046183000000000,2026-03-09 08:49:43,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Max Verstappen"", ""..."
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreifr2h6rxz6nc6v5x3ihftkjlozpli4kcgozg55ok...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-03-09T09:09:27.851Z,2026-03-09T09:00:00.000000Z,Jean-Michel Jarre eregast op jubileumeditie Am...,NaN,NaN,0,...,0,0,Jean-Michel Jarre eregast op jubileumeditie Am...,De Franse muziekpionier Jean-Michel Jarre komt...,https://www.rtl.nl/boulevard/artikel/5575922/j...,De 77-jarige Jean-Michel is vooral bekend van ...,1773046800000000000,2026-03-09 09:00:00,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Jean-Michel Jarre""..."
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreidp2ds4z266yhr43ogyd4h4dsay6xzqw2yis4l6x...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-03-09T09:09:33.149Z,2026-03-09T09:00:09.000000Z,Herfst komt de lente even verdringen: regenkle...,NaN,NaN,0,...,0,0,Herfst komt de lente even verdringen: regenkle...,😳☔️,https://www.metronieuws.nl/in-het-nieuws/binne...,Vooral landinwaarts schijnt vandaag nog lekker...,1773046809000000000,2026-03-09 09:00:09,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Weeronline"", ""acto..."

In [33]:
enriched_df.nr_actors_a.value_counts()
pol_df = enriched_df[enriched_df.nr_actors_a > 0]
pol_df.head()

right_isnull = pol_df[pol_df['nr_actors_right'].isnull()]['uri'].tolist()
left_isnull = pol_df[pol_df['nr_actors_left'].isnull()]['uri'].tolist()
center_isnull = pol_df[pol_df['nr_actors_center'].isnull()]['uri'].tolist()

df[df['uri'].isin(right_isnull)].news_actors.sample(n=5).values[0:5]

array(['{"actors": [{"actor_name": "MIVD-directeur Peter Reesink", "actor_function": "a", "actor_pp": ""}, {"actor_name": "AIVD-directeur-generaal Simone Smit", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de inlichtingendiensten", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de AIVD en MIVD", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "de Europese Rekenkamer", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de EU", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "ORF", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Zijn advocaat", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Weissmann", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Ingrid Thurnher", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Nederland", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "Openbaar Ministerie", "actor_function": "a", "actor_pp": ""}, {"actor_name": "regionale omroep Rijnmond", "actor_function": "b", "actor_pp": ""}, {"actor_name": "advocaat-generaal", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "President Donald Trump", "actor_function": "a", "actor_pp": ""}, {"actor_name": "bevriende politicus", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Critici in Iran", "actor_function": "d", "actor_pp": ""}, {"actor_name": "Tegenstanders", "actor_function": "d", "actor_pp": ""}, {"actor_name": "Basij-militie", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Norman Roule", "actor_function": "b", "actor_pp": ""}]}'],
      dtype=object)

In [34]:
df[df['uri'].isin(left_isnull)].news_actors.sample(n=5).values[0:5]

array(['{"actors": [{"actor_name": "Martin de Wit", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Christiaan Alberdingk Thijm", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Jaap Timmer", "actor_function": "b", "actor_pp": ""}, {"actor_name": "de politie", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "Wethouder Mussche", "actor_function": "a", "actor_pp": ""}, {"actor_name": "COA", "actor_function": "a", "actor_pp": ""}, {"actor_name": "RTV Oost", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Anne van den Hoek", "actor_function": "c", "actor_pp": ""}, {"actor_name": "De gemeente", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Het college van burgemeester en wethouders", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "de Europese Rekenkamer", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de EU", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "ORF", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Zijn advocaat", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Weissmann", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Ingrid Thurnher", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Nederland", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "Bernard Quintin", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Bart De Wever", "actor_function": "a", "actor_pp": ""}, {"actor_name": "De Luikse politie", "actor_function": "a", "actor_pp": ""}]}'],
      dtype=object)

In [43]:
right_notnull = pol_df[pol_df['nr_actors_right'] == 1]['uri'].tolist()
df[df['uri'].isin(right_notnull)].news_actors.sample(n=5).values[0:5]

array(['{"actors": [{"actor_name": "de korpsleiding", "actor_function": "a", "actor_pp": ""}, {"actor_name": "minister Van Weel", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de familie van Lisa", "actor_function": "d", "actor_pp": ""}, {"actor_name": "korpschef Janny Knol", "actor_function": "a", "actor_pp": ""}, {"actor_name": "plaatsvervangend korpschef Wilbert Paulissen", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Chris Jude", "actor_function": "d", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "Roel Schreinemachers", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Rob Jetten", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Dilan Yesilgöz", "actor_function": "a", "actor_pp": "VVD"}, {"actor_name": "Defensie", "actor_function": "a", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "Thierry Aartsen", "actor_function": "a", "actor_pp": "VVD"}, {"actor_name": "ZZP Nederland", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Frank Alfrink", "actor_function": "c", "actor_pp": ""}, {"actor_name": "FNV", "actor_function": "c", "actor_pp": ""}, {"actor_name": "VNO-NCW", "actor_function": "c", "actor_pp": ""}, {"actor_name": "MKB Nederland", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Mieke Ripken", "actor_function": "c", "actor_pp": ""}, {"actor_name": "AWVN", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Jannes van der Velde", "actor_function": "c", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "korpschef Janny Knol", "actor_function": "a", "actor_pp": ""}, {"actor_name": "plaatsvervangend korpschef Wilbert Paulissen", "actor_function": "a", "actor_pp": ""}, {"actor_name": "minister David van Weel", "actor_function": "a", "actor_pp": ""}, {"actor_name": "De Nederlandse Politiebond (NPB)", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Voorzitter Nine Kooiman", "actor_function": "c", "actor_pp": ""}]}',
       '{"actors": [{"actor_name": "justitieminister David van Weel", "actor_function": "a", "actor_pp": ""}, {"actor_name": "korpschef Janny Knol", "actor_function": "a", "actor_pp": ""}, {"actor_name": "plaatsvervangend korpschef Wilbert Paulissen", "actor_function": "a", "actor_pp": ""}, {"actor_name": "korpsleiding", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de Nederlandse Politiebond", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Nine Kooiman", "actor_function": "a", "actor_pp": ""}, {"actor_name": "de familie van Lisa", "actor_function": "d", "actor_pp": ""}, {"actor_name": "Autoriteit Persoonsgegevens", "actor_function": "a", "actor_pp": ""}]}'],
      dtype=object)

In [40]:
df[(df['uri'].isin(right_notnull)) & (df['news_actors'] == '{"actors": [{"actor_name": "Minister-president Rob Jetten", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Martin van Eijk", "actor_function": "c", "actor_pp": ""}, {"actor_name": "ADAC", "actor_function": "c", "actor_pp": ""}, {"actor_name": "een Nederlander", "actor_function": "d", "actor_pp": ""}]}')].news_content.values[0]

'Misschien is het je al opgevallen: de benzineprijzen zijn flink gestegen. De oorlog in het Midden-Oosten speelt daarin een belangrijke rol en leidt tot hoge brandstofkosten, wat veel vragen oproept. Moet de overheid de belastingen verlagen om het betaalbaar te houden?\n\nMinister-president Rob Jetten ziet daar voorlopig geen reden toe. In het televisieprogramma Nieuwsuur gaf hij aan dat hij de stijging van de prijzen voor benzine en diesel wel nauwlettend volgt, maar dat ingrijpen op dit moment nog niet aan de orde is, meldt Hart van Nederland.\n\nHogere prijzen aan de pomp\n\nWel zegt de premier begrip te tonen voor mensen die erg balen van de hoge benzineprijzen: „Het is impactvol als een oorlog ver weg thuis leidt tot hogere prijzen aan de pomp”, aldus Jetten in Nieuwsuur. Hij benadrukt wel iets anders: „We doen er alles aan om te zorgen dat de leveringszekerheid in Nederland overeind blijft.”\n\nOp de Amsterdamse gasbeurs steeg de gasprijs bij aanvang van de handel met 30 procent tot ongeveer 69 euro per megawattuur. De stijging volgt op een forse stijging van de olieprijs tot boven de 100 dollar per vat, nadat meer grote olieproducenten in het Midden-Oosten hun productie hebben teruggeschroefd.\n\nBetalen voor benzine\n\nWat zijn de prijzen nu precies? De adviesprijs voor een liter benzine ligt rond de 2,39 euro. Voor een liter diesel is dat ongeveer 2,44 euro. Voor diesel gaat het daarmee om een recordprijs.\n\nDrive, een brancheorganisatie van zo’n 1300 Nederlandse tank- en laadstations, ziet onder andere het tanktoerisme met ‘lede ogen aan’. De organisatie dringt erop aan dat het kabinet maatregelen neemt om de prijs van brandstoffen naar beneden te krijgen. „Het wordt zo langzamerhand onbetaalbaar”, zegt Martin van Eijk van Drive. Hij wil een lagere btw en een hoge accijnskorting op benzine en diesel, schrijft de NOS.\n\nOver de grens\n\nSinds het begin van de aanval van de Verenigde Staten en Israël op Iran stijgen de Nederlandse brandstofprijzen en gaan ook meer Nederlanders de grens over om te tanken. Vooral het tanktoerisme naar België is gestegen, omdat de benzine daar tot 70 cent per liter goedkoper is.\n\nOok in Duitsland tanken meer Nederlanders, al is het prijsverschil aan de pomp daar iets minder groot. „Jammer van die oorlog ginder, dat is natuurlijk niet zo leuk voor die mensen. Maar ja… het scheelt toch een berg geld buiten Nederland”, zegt een Nederlander die zijn tank volgooit in België tegen Omroep Zeeland.\n\nOok in België zijn de benzineprijzen gestegen, maar die lopen nog lang niet gelijk met Nederland. Waar een liter Euro 95 hier 2,37 euro kost, betaal je in België 1,59 euro. Ook in Duitsland zijn veel tankstations goedkoper, met prijzen onder de 2 euro per liter Euro 95. De ADAC, de Duitse tegenhanger van de ANWB, geeft wel aan dat tanken tijdens de ochtendspits vaak duurder is dan ’s avonds. De ADAC waarschuwt Nederlandse tanktoeristen dat de wachttijden aan de grens flink kunnen oplopen.\n\nDit zijn de best gelezen artikelen van dit moment:\n\nDe Spaarrekening van Daniela (33): ‘Die 180 euro wegenbelasting betaal ik nu makkelijk van mijn auto-spaarpotje’\n\nDe Nederlandsche Bank waarschuwt: haal contant geld in huis en spreid je geld over banken\n\nNiet Parijs of Rome: deze stad is volgens onderzoek dé Europese topbestemming van 2026\n\nNieuwe hypotheekcijfers: starters lenen steeds vaker groter bedrag dan doorstromers\n\nTanktoerisme: zoveel kun je besparen door over de grens te tanken\n\nReacties'

In [41]:
df[(df['uri'].isin(right_notnull)) & (df['news_actors'] == '{"actors": [{"actor_name": "Minister-president Rob Jetten", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Martin van Eijk", "actor_function": "c", "actor_pp": ""}, {"actor_name": "ADAC", "actor_function": "c", "actor_pp": ""}, {"actor_name": "een Nederlander", "actor_function": "d", "actor_pp": ""}]}')].uri.values[0]

'at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mgmp23p7st22'

In [42]:
enriched_df[enriched_df['uri'] == 'at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky.feed.post/3mgmp23p7st22']

,uri,nr_actors_b,nr_actors_c,nr_actors_a,nr_actors_d,nr_actors_total,nr_actors_right,nr_actors_center,nr_actors_left,nr_actors_political
183,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0,2,1,1,4,0.0,1.0,0.0,1.0

In [4]:
# see unique uri count
print(f"Unique URIs: {df['uri'].n_unique()}")

Unique URIs: 200

In [5]:
# print news actors columns first 5 rows
for i, row in enumerate(df[['news_content', 'news_actors']].head(5).iter_rows()):
    print(f"Row {i}: {row}")

Row 0: ('De Amerikaanse economie moet ook ons een zorg zijn\n\nDeze belasting op vermogen was een brevet van onvermogen\n\nCommentaar\n\n90 miljard voor Oekraïne is verdedigbaar, maar wees wel eerlijk: dat geld is weg\n\nCommentaar\n\n90 miljard voor Oekraïne is verdedigbaar, maar wees wel eerlijk: dat geld is weg\n\ncommentaar\n\n31\n\nWat is het plan B voor Oekraïense ontheemden nu oorlog voortduurt?\n\ncommentaar\n\n31\n\nWat is het plan B voor Oekraïense ontheemden nu oorlog voortduurt?', None)
Row 1: ("Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw", None)
Row 2: ('Met één zin schetst directeur Peter Bijvelds van FC Eindhoven de zin en onzin van een prijzenkast bij een kleinere club in het betaald voetbal. ‘Onze prijzenkast was te groot’, zegt Bijvelds, om even in te houden en de grap te laten landen: ‘Die hebben we aan PSV gegeven.’\n\nOver prijzenkasten in het betaald voetbal bestaan talloze anekdotes. De Volkskrant ging eens, bij een bezoek aan trainer Ruud Kaiser van FC Magdeburg, op zoek naar de toenmalige Europacup voor bekerwinnaars, in 1974 gewonnen in de Kuip, tegen AC Milan. Dat was het grootste succes in de historie van de diep weggezakte club uit de voormalige DDR. Waarom was die beker nergens uitgestald, om oude trots te laten voortleven?\n\nDe zoektocht leidde tot een uithoek van het kantoor van de administrateur, waar de beker in een kist achter een kastdeur stond. Vreemd.\n\nOud-voorzitter Michael van Praag van Ajax kon smakelijk vertellen over Torino, tegenstander van Ajax in de finale van de Uefa Cup in 1992. Bij het traditionele diner op de vooravond van de eerste wedstrijd in Turijn schepte eigenaar Aldo Spinelli nogal op over zijn club. Over investeringen, salarissen en transfersommen, allemaal veel hogere bedragen dan bij Ajax rondgingen.\n\nTwee weken later was de tweede finale, in Amsterdam. Ajax had de tafel chic gedekt, in de bestuurskamer van het oude stadion De Meer, en liet de leiding van Torino tegenover de overvolle prijzenkast zitten, met allemaal Europese trofeeën en de wereldbeker. Spinelli moest, nadat hij bijna was verblind door het schijnsel van zilverwerk, toegeven dat Ajax wel een mooi clubje was.\n\nMeer verliezers dan winnaars\n\nAjax was destijds een veelwinnaar, maar er zijn meer verliezers dan winnaars in het voetbal. Het kampioenschap in de eredivisie is voor slechts enkele clubs weggelegd.\n\nDe beker, met een grotere toevalsfactor door het knock-outsysteem, biedt meer kansen. Dit seizoen bereikten drie clubs van buiten de traditionele top drie de halve finales. En wie de beker wint, mag in augustus tegen de landskampioen voetballen om de Johan Cruijff Schaal.\n\nDaarnaast zijn in de eerste divisie nog periodetitels te winnen of natuurlijk het algehele kampioenschap. De tweede plaats is ook goed voor promotie.\n\nAZ – Telstar is woensdag de tweede halve finale van het bekertoernooi, na NEC – PSV van dinsdag. De succesvolle subtopper AZ tegen een nieuwkomer aan het prijzenfront, de witte hemelbestormers uit Velsen-Zuid.\n\nTelstar in de buurt van een prijs, dat is sowieso nieuws. Telstar promoveerde vorig seizoen na 47 jaar naar de eredivisie, zonder een periodetitel te hebben gewonnen overigens, door via de reguliere stand door te stromen naar een vacante plek in de nacompetitie. Voor de onverwachte promotie kreeg Telstar een schild, een van de eerste prijzen in de clubgeschiedenis.\n\nOp de bestuurskamer\n\nMaar is daar een aparte prijzenkast voor gemaakt? Nee. Er waren andere prioriteiten. Directeur Leon Annokkee antwoordt op de vraag om de prijzenkast te mogen fotograferen: ‘Alle prijzen staan op mijn kamer.’\n\nHet schild dus, plus een paar keer de trofee voor het Visserijtoernooi, traditioneel met Koninklijke HFC en Katwijk. Plus de zogenoemde ‘Kist Cup’, al is dat een schild met de afbeelding van het karakteristieke hoofd van de vroegere trainer Simon Kistemaker, als beloning voor een onregelmatig gehouden confrontatie tussen twee voormalige clubs van Kistemaker.\n\n‘Telstar – De Graafschap. Seizoen 2022-2023’, staat op het schild. Na twee duels was de stand precies gelijk. Telstar kreeg de trofee omdat oud-Telstar in het voorprogramma van oud-De Graafschap won.\n\nTelstar is in 1963 voortgekomen uit de amateurclubs VSV en Stormvogels en promoveerde eerder in 1964 naar de eredivisie, toen als nummer twee. Een kampioenschap is nooit behaald, de beker is sinds 1963 nooit gewonnen.\n\nIn de kluis\n\nOok bij AZ, de ambitieuze club van 25 kilometer verderop, is er geen overdaad aan prijzen te bekennen. Twee landstitels in de eredivisie is al fantastisch, behaald in financiële hoogtijdagen met de broers Molenaar (1981) en Dirk Scheringa (2009) als eigenaars.\n\nRond het stadion, op de rode buitenkant, staan de jaartallen en afbeeldingen van alle prijzen (vier bekers). Maar dat gaat veranderen, want na een enquête onder supporters is besloten dat er meer afbeeldingen van spelers komen. Alle fysieke prijzen voor titels en bekers zijn tijdelijk opgeslagen in een kluis vanwege een verbouwing van de bestuurskamer.\n\nMaar op het jeugdcomplex in Wijdewormer staat een mooie vitrine met de trofee van de Youth League, de Champions League voor jeugd, drie jaar geleden gewonnen. Mooi uitgestald in de kantine, om de nieuwe aanwas van talent te motiveren. Ze zien rond elke training die bokaal, omringd door foto’s van onder anderen Kees Smit, tegenwoordig de ster in de dop van het eerste elftal.\n\nMax Huiberts, die na ruim tien jaar vertrekt als technisch directeur, zou graag afscheid nemen met de bekerwinst voor het eerste elftal. AZ won in zijn periode geen prijs bij de senioren, ondanks grote successen met de opleiding en honderden miljoenen aan inkomsten van transfers.\n\nMuseumplan\n\nTelstar won dus nog veel minder dan AZ. Lon Weijers, archivaris van de club: ‘We hebben een eremedaille van de gemeente Velsen, voor de promotie naar de eredivisie in 1964.’\n\nWeijers vertelt over zijn plan van een aantal jaren geleden om een prijzenkast te plaatsen. Hij was er helemaal uit met de architect, over waar en hoe, maar Weijers vertrok voor een tijd naar het buitenland en het plan raakte in de vergetelheid.\n\nNu hij hoort van de foto’s voor de krant snapt hij dat telefoontje van Annokkee, of hij de prijzen even naar de club wilde brengen. Weijers is zuinig met het erfgoed, zeker zolang er geen vaste plek is om het uit te stallen. Er is een idee over een museum.\n\nZware wisselbeker\n\nTrouwens, in zekere zin heeft Telstar wel degelijk de beker gewonnen, ver voor de oprichting zelfs. Voorloper VSV versloeg in 1938 AGOVV in de finale van de zogenoemde Holdertbeker, de voorganger van de KNVB-beker, naar een initiatief van Hak Holdert.\n\nVoorzitter Hans Stoelman van VSV vertelt over de wisselbeker, waarvan een aantal clubs later een replica kreeg. De loodzware beker staat in de bestuurskamer en krijgt straks op een nieuw complex een mooi plekje.\n\nAmateurclubs hebben vaak heel grote en protserige prijzenkasten, met een keur aan bekers en andere trofeeën, ook gewonnen door jeugdploegen, soms met weinig hiërarchie in de opstelling.\n\nVoor de betaalde club is de prijs zeldzaam. Go Ahead Eagles boekte afgelopen seizoen het grootste succes in de clubgeschiedenis door de beker te winnen. Onlangs was Telstar te sterk in de kwartfinales. AZ doet zelfs nog om twee prijzen mee, de beker en de Conference League, met volgende week de eerste achtste finale tegen Sparta Praag.\n\nSterspeler Kees Smit begrijpt de kritiek van de supporters op het wisselvallige spel dit seizoen, omdat ze meer verwachten, en dat is terecht. Maar reken maar dat ze gebrand zijn, woensdag tegen Telstar. ‘We zijn er heel erg mee bezig, om een prijs te winnen met zijn allen. We kennen elkaar heel goed. We hebben zin in die wedstrijd tegen Telstar, en wat daarna nog kan komen. Ook in de Conference League hebben we kans om ver te komen, al zijn veel ploegen op papier beter dan wij.’', '{"actors": [{"actor_name": "Peter Bijvelds", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Aldo Spinelli", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Leon Annokkee", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Lon Weijers", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Hans Stoelman", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Kees Smit", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Michael van Praag", "actor_function": "b", "actor_pp": ""}]}')
Row 3: ('Chris Stoffer heeft een glorieuze week achter de rug. De leider van de kleine oppositiepartij trok via een motie alle aandacht naar zich toe in de hoogoplopende discussie over de verhoging van de AOW-leeftijd. Na het debat over de regeringsverklaring kondigde een talkshow hem ronkend aan: ‘SGP-leider Chris Stoffer maakt furore met zijn AOW-motie.’\n\nStoffer leek het er niet mee oneens. De SGP’er voerde aan tafel het hoogste woord over hoe volgens hem de voorgenomen verhoging van de AOW-leeftijd afgezwakt kan worden. De eveneens aanwezige minister van Financiën Eelco Heinen hoorde het gedwee aan. Zo is het afgesproken: bewindslieden moeten hun ego opzij zetten en de oppositie af en toe laten shinen. Alleen zo kan het minderheidskabinet overleven.\n\nAl voor het aantreden van Rob Jetten viel te horen dat ‘motiemanagement’ een belangrijke rol zou gaan spelen. De gedachte erachter is simpel. In een versplinterd politiek landschap heerst er onder oppositiepartijen een meedogenloze strijd om aandacht – de belangrijkste valuta van de hedendaagse politiek. Door op strategische momenten een motie aan een meerderheid te helpen, kunnen D66, VVD en CDA een oppositiepartij voor even een plekje in de zon gunnen.\n\nVoor de buitenwereld zal het als iets futiels overkomen, maar in de Haagse binnenwereld kan een aangenomen motie een zeldzaam moment van succes zijn. Als de coalitie daarbij kan helpen zonder een hoge prijs te betalen: waarom niet?\n\nNiet voor niets knalden afgelopen week nog net niet de champagnekurken bij de afgesplitste fractie van Gidi Markuszower (voorheen PVV), die medeondertekenaar was bij de AOW-motie van Stoffer. Markuszower mocht voor de camera’s uitleggen wat zijn ‘deal’ met de coalitie inhield.\n\nIets vergelijkbaars gebeurde bij een motie van ChristenUnie-leider Mirjam Bikker, die het kabinet opriep om maatregelen te nemen om de stijging van de armoede tegen te gaan. Ook deze motie werd aan een meerderheid geholpen door de coalitie. Bikker mocht ermee pronken op sociale media. D66-fractievoorzitter Jan Paternotte zette haar zondag bij de talkshow Buitenhof nog even in het zonnetje als toonbeeld van constructief oppositievoeren.\n\nEen omgekeerd effect is er ook. Partijen die geen meerderheid krijgen, worden al snel weggezet als verliezers en afgewezen bruiden. GroenLinks-PvdA verkeert vooralsnog geregeld in die positie, met de PVV en SP als ongemakkelijke compagnons. De partij van Jesse Klaver blijft er zelf laconiek onder. GroenLinks-PvdA is ervan overtuigd dat de afgewezen moties, bijvoorbeeld over het volledig ongedaan maken van de verhoging van de AOW-leeftijd, uiteindelijk hun politieke waarde zullen hebben. Aan linkse kiezers kan zo getoond worden dat Rob Jetten als premier keer op keer kiest voor rechts en zelfs het radicaal-rechts van Markuszower.\n\nDe coalitie zal het verdeel-en-heers via moties de komende maanden alleen maar verder opvoeren, zo is de verwachting, ook omdat er voorlopig nog weinig concreet beleid voorligt. Wijlen NRC-commentator Marc Chavannes wordt nog weleens aangehaald met de bon mot dat ieder belangrijk politiek debat in Nederland eindigt in een verhoging van de benzineaccijns. Nu geldt eerder: de wereld kan in brand staan, maar de Nederlandse politiek is druk met moties, hoe ongrijpbaar soms ook.\n\nDat geldt zeker ook voor de motie-Stoffer van de afgelopen week. De verhoging van de AOW-leeftijd moet versoepeld worden, zo luidt het verzoek aan het kabinet, maar onduidelijk blijft hoeveel dat gaat kosten en waar het geld vandaan moet komen. De bezuiniging van 2,7 miljard euro vanaf 2033 staat nog steeds in de boeken.\n\nCDA-leider Henri Bontenbal ageerde in 2024 nog hartstochtelijk tegen de Haagse obsessie met moties. Hij pleitte voor een quotum van maximaal twee moties per partij per debat. Ook kondigde hij aan dat zijn fractie niet meer zou meestemmen met moties die alleen bedoeld waren om ‘makkelijk te scoren’. Het meest verafschuwde de CDA’er ‘de gratis-biermoties’. ‘Een fractie verzoekt de regering in deze motie iets te doen wat geld kost, maar vertelt er niet bij waar dat geld vandaan moet komen’, aldus de definitie die de CDA-leider zelf gaf.\n\nIn die periode trok Bontenbal ook nog hard van leer tegen BBB-voorvrouw Caroline van der Plas die het kabinet in een motie had opgeroepen om het minimumloon ‘enigszins te verhogen’. Hij noemde dat ‘een grove gratis-biermotie’. ‘Als je als partij een beetje financieel degelijk bent, kom je met een verhaal bij welk potje er iets bij moet en bij welk potje er dan iets afgaat.’\n\nNu ‘motiemanagement’ onderdeel is geworden van de overlevingsstrategie van zijn minderheidskabinet doet Bontenbal minder moeilijk. Hij stemde voor de motie-Stoffer, hoewel niet duidelijk wordt uit welk potje de versoepeling van de AOW-maatregel betaald gaat worden. Volgens het CDA is er desondanks geen sprake van een gratis-biermotie: er zou ‘geen directe financiële claim’ zijn.', '{"actors": [{"actor_name": "Buitenhof", "actor_function": "d", "actor_pp": ""}, {"actor_name": "Chris Stoffer", "actor_function": "a", "actor_pp": "SGP"}, {"actor_name": "Gidi Markuszower", "actor_function": "a", "actor_pp": "PVV"}, {"actor_name": "Henri Bontenbal", "actor_function": "a", "actor_pp": "CDA"}, {"actor_name": "Caroline van der Plas", "actor_function": "a", "actor_pp": "BBB"}, {"actor_name": "CDA", "actor_function": "a", "actor_pp": "CDA"}]}')

In [7]:
# print news actors columns last 5 rows
for i, row in enumerate(df[['news_content', 'news_actors']].tail(5).iter_rows()):
    print(f"Row {i}: {row}")

Row 0: ('Demi Lovato vindt het achteraf "niet oké" dat ze op achttienjarige leeftijd een relatie met de twaalf jaar oudere acteur Wilmer Valderrama had. De actrice en zangeres kijkt er anders tegenaan nu ze zélf dertig jaar is.\n\n"Mensen van mijn leeftijd begrepen me toen niet", zegt Lovato in de podcast Baby, This Is Keke Palmer. "Maar nu weet ik dat het niet oké is."\n\nLovato begon al op jonge leeftijd met acteren. Ze leefde door haar drukke werkschema naar eigen zeggen meer als een volwassene dan als een tiener. Daardoor zocht ze vooral contact met oudere mensen.\n\n"Als je me als een volwassene behandelt, ga ik me ook als een volwassene gedragen", zegt Lovato in de podcast over wat ze zichzelf destijds voorhield. Die houding leidde er volgens haar toe dat ze al vroeg in de problemen kwam door onder meer drugsgebruik.\n\nLovato werd bekend door haar rollen in de Camp Rock-films op Disney Channel en de televisieserie Sonny with a Chance. Als zangeres is ze bekend van nummers als Sky Scraper en Heart Attack.', '{"actors": [{"actor_name": "Demi Lovato", "actor_function": "b", "actor_pp": ""}]}')
Row 1: ('Bij een eenzijdig ongeval op de Almelosestraat (N741) in Ambt Delden zijn woensdagochtend twee personen om het leven gekomen. Het gaat om een man en een vrouw, meldt de politie.\n\nHet ongeval gebeurde woensdagochtend rond 08.00 uur. De politie heeft de weg afgesloten en doet uitgebreid onderzoek naar de oorzaak van het ongeval.', '{"actors": [{"actor_name": "de politie", "actor_function": "a", "actor_pp": ""}]}')
Row 2: ("Droevig nieuws van Polymarket, het in Nederland illegale wedkantoor dat Alexander Klöpping laatst deed geloven dat hij verstand heeft van politiek. Dat bedrijf heeft namelijk de mogelijkheid om geld te verdienen met een nucleaire apocalyps weer ingetrokken. Dit, nadat er ophef was ontstaan over de mogelijkheid om weddenschappen af te sluiten over de vraag wanneer er ergens in de wereld een kernbom af zou gaan. Erg flauw natuurlijk, want wat is er nou leuker dan 's ochtends uit je bed worden gekernbombardeerd in een totale nucleaire apocalyps, en daarna 's middags in de overgebleven ruïnes van wat ooit de Westerse beschaving was op zoek gaan naar degene die juridisch aansprakelijk gehouden kan worden voor jouw claim van 20 tegen 1 met een inzet van 14 dollar terwijl je al je dode vrienden appt dat jij al die tijd toch gelijk hebt gehad. Bovendien kunnen we nu niet meer profiteren van de onfeilbare wisdom of the crowds die deze wedkantoren pretenderen te openbaren, terwijl de crowds afgelopen week nog 553.000 dollar kwijtraakten aan user 'Magamyman' die al wat vroege wisdom over de dood van Ali Khamenei leek te hebben. Allemaal ontzettend village gedrag van mensen die de river niet in durven.\n\n[LIVEBLOG IRAN HIER]", '{"actors": [{"actor_name": "Alexander Klöpping", "actor_function": "b", "actor_pp": ""}, {"actor_name": "user \'Magamyman\'", "actor_function": "d", "actor_pp": ""}]}')
Row 3: ('De rechtszaak tegen Marius Borg Høiby gaat woensdag verder met de verklaring van een nieuw slachtoffer. Het gaat om een vrouw die door de zoon van de Noorse kroonprinses Mette-Marit zou zijn mishandeld en met wie hij recent nog een relatie had. Tijdens haar getuigenis moet Høiby op een andere plek dan gebruikelijk zitten, zodat hij haar niet kan aankijken, melden Noorse media.\n\nRoyaltyredactie\n\nHøiby heeft sinds hij vorig jaar augustus een contactverbod kreeg opgelegd, het verbod meermaals geschonden, zelfs enkele dagen voor het begin van de rechtszaak. Dat laatste zorgde ervoor dat hij sindsdien in voorarrest zit.\n\nTijdens het tot nu toe vijf weken durende proces reageerde Høiby meerdere keren geëmotioneerd wanneer de relatie met de vrouw ter sprake kwam. Zijn advocaten zeggen dat het onduidelijk is wat de huidige relatie tussen de twee is en of Høiby en de vrouw zichzelf nog steeds als geliefden beschouwen. „Het is vrij duidelijk dat er nog steeds gevoelens in het spel zijn, maar welke dat zijn moet hij zelf uitleggen”, zegt advocaat Petar Sekulic.\n\nLees ook: Noorse ‘bonusprins’ Marius tijdens rechtszaak: ‘Ex-vriendin mogelijk wel eens een klap gegeven’\n\nDe zoon van de Noorse kroonprinses wordt beschuldigd van tientallen strafbare feiten, waaronder mishandeling en verkrachting. Het proces tegen hem ging begin februari van start.\n\nLees meer over het Koninklijk Huis en wereldwijde royalty op onze speciale pagina.\n\nBekijk hier al onze video’s over het Koninklijk Huis:\n\n\u200c\n\nLees meer\n\nZoon van Cher opnieuw gearresteerd voor woninginbraak\n\nZoon van Cher opnieuw gearresteerd voor woninginbraak\n\nRapper Diddy komt 1,5 maand eerder vrij door deelname afkickprogramma\n\nRapper Diddy komt 1,5 maand eerder vrij door deelname afkickprogramma\n\n‘Wuthering Heights’-gekte barst los: nieuwe film lokt massa toeristen naar Brits dorpje\n\n‘Wuthering Heights’-gekte barst los: nieuwe film lokt massa toeristen naar Brits dorpje\n\nMaak kans op 2 kaarten voor LUMINISCENCE\n\nMaak kans op 2 kaarten voor LUMINISCENCE\n\nPianist en componist Jan Huydts (89) overleden\n\nPianist en componist Jan Huydts (89) overleden\n\nStudio 100 schuift choreograaf aan de kant na meldingen van grensoverschrijdend gedrag\n\nStudio 100 schuift choreograaf aan de kant na meldingen van grensoverschrijdend gedrag', '{"actors": [{"actor_name": "advocaat Petar Sekulic", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Noorse media", "actor_function": "b", "actor_pp": ""}]}')
Row 4: ('Raymond Mens is geschrokken van de uitgelekte appjes van Geert Wilders. Hij zegt aan de bar van het invloedrijke Vandaag Inside dat hij de PVV-leider ‘niveauloos’ vindt. “Het is echt een blunder.”\n\nDe Volkskrant publiceerde afgelopen weekend appberichten van Geert Wilders zelf, waaruit blijkt dat de PVV-leider in aanloop naar de afgelopen verkiezingen ‘een smoes’ zocht om niet te hoeven deelnemen aan verkiezingsdebatten ‘zonder dat ze me voor lafaard uitmaken’. Hij verzocht zijn oud-rechterhand Gidi Markuszower ‘een list te verzinnen’.\n\nPlease, please, please\n\nWilders wilde in elk geval niet naar het RTL-debat. “Please, please, please”, appte hij aan Gidi, die inmiddels uit de fractie is gestapt. Een kwartier daarna vernam Wilders uit Belgische media dat óók hij op een lijst stond van jihadisten die een aanslag op de Belgische premier Bart de Wever hadden voorbereid, maar al vroegtijdig waren opgepakt.\n\nHoewel de NCTV hem liet weten dat er ‘geen restdreiging’ was, greep Wilders dit uiteindelijk aan om het RTL-debat te annuleren. Door de afzegging van Wilders is D66-leider Rob Jetten uiteindelijk minister-president geworden. Hij mocht namelijk in zijn plaats meedoen aan het RTL-debat en dat leverde hem een spurt op in de peilingen.\n\nHeel relevant\n\nEr is commentaar op Gidi Markuszower, omdat hij de appjes heeft gelekt, maar daar denkt Raymond Mens anders over. “Ik vind het wel heel relevant dat Wilders nu dag in dag uit tegen Rob Jetten tekeergaat, maar die beslissing van hem om niet naar dat debat te gaan, heeft Rob Jetten premier gemaakt. Dat is natuurlijk wel heel relevante informatie.”\n\nWilfred Genee daarop in Vandaag Inside: “Ja, hij stond op 14 zetels voor het RTL-debat, hè, D66.”\n\nRaymond: “Ja, de meest gestelde vraag aan Jetten tijdens interviews was — hij zat ook bij Eva een paar dagen voor dat debat: ‘Waarom gaat het zo slecht met uw campagne?’”\n\nNiet in vorm\n\nDe D66-campagne ging op volle toeren draaien door de afzegging van Wilders. “Ja, dat veranderde in één avond tijdens dat RTL-debat. En als Wilders daar dan verantwoordelijk voor is…”, aldus Raymond.\n\nPolitiek verslaggever Jeanneau van Beurden: “Dit heeft hem heel goed gedaan.”\n\nJohan Derksen: “Ik begrijp ook niet dat Wilders niet naar een debat wil, want daar is hij juist de beste in.”\n\nWilfred: “Ja, maar hij was niet in vorm en je voelde ook dat hij wat vermoeid was. Je merkte al een soort sleetsheid erop.”\n\nNiveauloos\n\nRené van der Gijp denkt daar hetzelfde over. “Ja, normaal kon hij anderen aanvallen en nu werd hij de hele tijd zélf aangevallen. Daar word je niet blij van.”\n\nRaymond: “Als jij toch naar een Kamerlid stuurt: ‘Please, please, please, heb je voor mij een excuus?’, dat is toch niveauloos?”\n\nTafelgast Job Knoester: “Dan kun je beter stoppen als je er zo in staat. Dan moet je op tijd eruit stappen.”\n\nJohan besluit: “Het is echt een blunder van Wilders dit.”', '{"actors": [{"actor_name": "Raymond Mens", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Geert Wilders", "actor_function": "a", "actor_pp": "PVV"}, {"actor_name": "Gidi Markuszower", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Rob Jetten", "actor_function": "a", "actor_pp": "D66"}, {"actor_name": "Wilfred Genee", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Jeanneau van Beurden", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Johan Derksen", "actor_function": "b", "actor_pp": ""}, {"actor_name": "René van der Gijp", "actor_function": "b", "actor_pp": ""}, {"actor_name": "Job Knoester", "actor_function": "b", "actor_pp": ""}]}')

## 1) Fetch recent posts into SQLite

- Adjust `--max-age-days` to control the time window.
- Upsert ensures engagement metrics refresh over time.
- You can also call the fetcher via CLI if you prefer.

In [ ]:
import os
os.getcwd()

'/data/storage100gb5/blueskyranker'

In [15]:
fetcher = Fetcher()
result = fetcher.fetch(max_age_days=2, 
                       extract_articles=True, 
                       handles=['news-flows-nl.bsky.social'])  
print(result)

Posts fetched (all handles): 0post [00:00, ?post/s]

Posts fetched (all handles): 1post [00:01,  1.56s/post]



Handles: 100%|██████████| 1/1 [00:02<00:00,  2.05s/handle]
Posts fetched (all handles): 1post [00:02,  2.05s/post]

✅ DONE news-flows-nl.bsky.social: upserted 1 posts into SQLite

========================================================================
FINAL REPORT
========================================================================

Handle: news-flows-nl.bsky.social
  Pages fetched         : 2
  Posts fetched         : 1
    - originals         : 1
    - replies           : 0
    - reposts           : 0
  Engagement (sums)
    - likes             : 0
    - reposts           : 0
    - replies           : 0
    - quotes            : 0
  Engagement (averages per post)
    - likes             : 0.00
    - reposts           : 0.00
    - replies           : 0.00
    - quotes            : 0.00
  Time range            : 2026-03-03T15:00:00+00:00  →  2026-03-03T15:00:00+00:00
  Time taken            : 2.04s
  Effective rate        : 0.49 posts/sec

------------------------------------------------------------------------
All handles combined
------------------------------------------------------------------------
  Total pages           : 2
  Total posts           : 1
    - originals         : 1
    - replies           : 0
    - reposts           : 0
  Engagement (sums)
    - likes             : 0
    - reposts           : 0
    - replies           : 0
    - quotes            : 0
  Engagement (averages per post)
    - likes             : 0.00
    - reposts           : 0.00
    - replies           : 0.00
    - quotes            : 0.00

## 2) Load posts from SQLite

- Choose a handle you want to rank.
- You can limit rows or change ordering as needed.

In [4]:
import os
os.getcwd()

# go in blueskyranker directory
os.chdir('blueskyranker')

In [5]:
conn = ensure_db('newsflows.db')
handle = 'news-flows-nl.bsky.social'  # pick one of your handles
data = load_posts_df(conn, handle = handle, order_by='createdAt', descending=False)
data.head()

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uri       ┆ cid       ┆ author_ha ┆ author_di ┆ … ┆ news_desc ┆ news_uri  ┆ news_cont ┆ createdA │
│ ---       ┆ ---       ┆ ndle      ┆ d         ┆   ┆ ription   ┆ ---       ┆ ent       ┆ t_ns     │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆ str       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ at://did: ┆ bafyreibt ┆ news-flow ┆ did:plc:t ┆ … ┆ Walter De ┆ https://w ┆ Walter    ┆ 17718445 │
│ plc:toz4n ┆ uqhmon23l ┆ s-nl.bsky ┆ oz4no26o2 ┆   ┆ Donder    ┆ ww.rtl.nl ┆ heeft     ┆ 30000000 │
│ o26o2x4vs ┆ vox7jlmlt ┆ .social   ┆ x4vsbum7c ┆   ┆ (64)      ┆ /boulevar ┆ meerdere  ┆ 000      │
│ bum…      ┆ vgj…      ┆           ┆ p4b…      ┆   ┆ vertolkt… ┆ d/a…      ┆ keren ge… ┆          │
│ at://did: ┆ bafyreibu ┆ news-flow ┆ did:plc:t ┆ … ┆ De BBC    ┆ https://w ┆ Volgens   ┆ 17718446 │
│ plc:toz4n ┆ knswavioe ┆ s-nl.bsky ┆ oz4no26o2 ┆   ┆ heeft     ┆ ww.rtl.nl ┆ verschill ┆ 27000000 │
│ o26o2x4vs ┆ nuoo52ifw ┆ .social   ┆ x4vsbum7c ┆   ┆ excuses   ┆ /boulevar ┆ ende      ┆ 000      │
│ bum…      ┆ 6t4…      ┆           ┆ p4b…      ┆   ┆ aangebode ┆ d/a…      ┆ media wa… ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│ at://did: ┆ bafyreidu ┆ news-flow ┆ did:plc:t ┆ … ┆ 200 euro  ┆ https://w ┆ Als       ┆ 17718447 │
│ plc:toz4n ┆ hncyrfjrk ┆ s-nl.bsky ┆ oz4no26o2 ┆   ┆ per jaar  ┆ ww.metron ┆ bedrijven ┆ 00000000 │
│ o26o2x4vs ┆ jkg4ukchg ┆ .social   ┆ x4vsbum7c ┆   ┆ halen,    ┆ ieuws.nl/ ┆ een       ┆ 000      │
│ bum…      ┆ q5g…      ┆           ┆ p4b…      ┆   ┆ zou m…    ┆ gel…      ┆ laadpaal  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ heb…      ┆          │
│ at://did: ┆ bafyreiam ┆ news-flow ┆ did:plc:t ┆ … ┆ In dit    ┆ https://w ┆ analyse   ┆ 17718447 │
│ plc:toz4n ┆ ydkdhby6v ┆ s-nl.bsky ┆ oz4no26o2 ┆   ┆ topseizoe ┆ ww.ad.nl/ ┆           ┆ 60000000 │
│ o26o2x4vs ┆ oqbb6anhz ┆ .social   ┆ x4vsbum7c ┆   ┆ n van NEC ┆ voetbal/m ┆ Verstoppe ┆ 000      │
│ bum…      ┆ j6l…      ┆           ┆ p4b…      ┆   ┆ gaat…     ┆ an-…      ┆ rtje      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ spelen …  ┆          │
│ at://did: ┆ bafyreicc ┆ news-flow ┆ did:plc:t ┆ … ┆ In dit    ┆ https://w ┆ praat     ┆ 17718447 │
│ plc:toz4n ┆ 4eqq6hiul ┆ s-nl.bsky ┆ oz4no26o2 ┆   ┆ topseizoe ┆ ww.ad.nl/ ┆ mee!      ┆ 71000000 │
│ o26o2x4vs ┆ dkzcr7uce ┆ .social   ┆ x4vsbum7c ┆   ┆ n van NEC ┆ voetbal/v ┆           ┆ 000      │
│ bum…      ┆ 3i2…      ┆           ┆ p4b…      ┆   ┆ gaat…     ┆ an-…      ┆ ‘Feyenoor ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ d is      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ erba…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
import pandas as pd
df = pd.DataFrame(data, columns=data.columns)
print(df.shape)
df.head()

(3449, 19)

,uri,cid,author_handle,author_did,indexedAt,createdAt,text,reply_root_uri,reply_parent_uri,is_repost,like_count,repost_count,reply_count,quote_count,news_title,news_description,news_uri,news_content,createdAt_ns
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreibtuqhmon23lvox7jlmltvgj5jv3cdwz52n6aahf...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-02-23T11:28:28.851Z,2026-02-23T11:02:10.000000Z,Walter De Donder ziet doorstart Kabouter Plop ...,NaN,NaN,0,0,0,0,0,Walter De Donder ziet doorstart Kabouter Plop ...,Walter De Donder (64) vertolkt sinds 1997 de r...,https://www.rtl.nl/boulevard/artikel/5569256/w...,Walter heeft meerdere keren gesprekken gevoerd...,1771844530000000000
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreibuknswavioenuoo52ifw6t4rv7dzdc2mze436my...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-02-23T11:28:32.658Z,2026-02-23T11:03:47.000000Z,BBC zegt sorry voor racistische uitroep tijden...,NaN,NaN,0,0,0,0,0,BBC zegt sorry voor racistische uitroep tijden...,De BBC heeft excuses aangeboden voor een racis...,https://www.rtl.nl/boulevard/artikel/5570710/b...,Volgens verschillende media was het de Schotse...,1771844627000000000
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreiduhncyrfjrkjkg4ukchgq5gkas3ec4xdooshmtw...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-02-23T11:21:04.152Z,2026-02-23T11:05:00.000000Z,Je kunt geld verdienen aan stroom van je laadp...,NaN,NaN,0,0,0,0,0,Je kunt geld verdienen aan stroom van je laadpaal,"200 euro per jaar halen, zou moeten kunnen.",https://www.metronieuws.nl/geld-carriere/2026/...,"Als bedrijven een laadpaal hebben, kunnen zij ...",1771844700000000000
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreiamydkdhby6voqbb6anhzj6lyq7ltikzd3qh4sec...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-02-23T12:26:39.949Z,2026-02-23T11:06:00.000000Z,Man van de wedstrijd tegen Feyenoord en Ajax: ...,NaN,NaN,0,0,0,0,0,Man van de wedstrijd tegen Feyenoord en Ajax: ...,In dit topseizoen van NEC gaat het vaak over K...,https://www.ad.nl/voetbal/man-van-de-wedstrijd...,analyse\n\nVerstoppertje spelen en hopen op be...,1771844760000000000
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,bafyreicc4eqq6hiuldkzcr7uce3i2wlakkqwfhj7kuy5f...,news-flows-nl.bsky.social,did:plc:toz4no26o2x4vsbum7cp4bxp,2026-02-23T11:20:57.053Z,2026-02-23T11:06:11.000000Z,Van de woestijn naar Ajax-beul: waarom het vak...,NaN,NaN,0,1,1,0,0,Van de woestijn naar Ajax-beul: waarom het vak...,In dit topseizoen van NEC gaat het vaak over K...,https://www.ad.nl/voetbal/van-de-woestijn-naar...,"praat mee!\n\n‘Feyenoord is erbarme­lijk, maar...",1771844771000000000

In [10]:
# get brand from url between https:// and / 
df['brand'] = df['news_uri'].str.extract(r'https?://([^/]+)/')
df[['news_uri', 'brand']].head()
df.brand.value_counts(dropna=False)

brand
www.ad.nl              949
www.rtl.nl             936
www.nu.nl              623
www.nrc.nl             289
nos.nl                 257
www.volkskrant.nl      204
www.metronieuws.nl      97
www.geenstijl.nl        65
www.mediacourant.nl     27
www.manners.nl           1
www.jmouders.nl          1
Name: count, dtype: int64

In [ ]:
# calculate word count for news_content if not null
df['word_count'] = df['news_content'].apply(lambda x: len(x.split()) if pd.notnull(x) else 0)
# get the first 10 characters of news_content to check
df['first_10_chars'] = df['news_content'].str[:10]

In [62]:
# describe word_count per brand
df.groupby('brand')['word_count'].describe()

,count,mean,std,min,25%,50%,75%,max
brand,,,,,,,,
nos.nl,257.0,344.945525,200.699745,0.0,216.00,319.0,457.00,880.0
www.ad.nl,949.0,480.746048,500.696338,0.0,73.00,337.0,726.00,2723.0
www.geenstijl.nl,65.0,322.646154,404.813400,74.0,148.00,200.0,274.00,2032.0
www.jmouders.nl,1.0,971.000000,NaN,971.0,971.00,971.0,971.00,971.0
www.manners.nl,1.0,539.000000,NaN,539.0,539.00,539.0,539.00,539.0
www.mediacourant.nl,27.0,352.888889,83.936942,244.0,290.00,331.0,442.00,515.0
www.metronieuws.nl,97.0,435.680412,354.329047,22.0,176.00,408.0,572.00,2296.0
www.nrc.nl,289.0,324.325260,578.861597,0.0,0.00,0.0,545.00,3104.0
www.nu.nl,623.0,297.208668,559.435563,2.0,74.50,219.0,317.50,6740.0
www.rtl.nl,936.0,168.326923,231.956178,0.0,44.00,44.0,225.25,2491.0
www.volkskrant.nl,204.0,888.696078,984.649629,0.0,459.25,656.0,878.75,9631.0

In [63]:
mask = (df['brand'] == 'www.nrc.nl') & (df['word_count'] <2)
df[mask][['news_uri']].values[0:5]

array([['https://www.nrc.nl/nieuws/2026/02/23/wat-zegt-een-schilderijlijst-donald-trump-wil-ze-van-goud-maar-17de-eeuwse-hollanders-kozen-juist-zwart-a4920740'],
       ['https://www.nrc.nl/nieuws/2026/02/23/zonder-de-eigenzinnige-kunstenaar-alejandro-jodorowsky-zouden-veel-hollywood-films-er-anders-uit-hebben-gezien-a4920869'],
       ['https://www.nrc.nl/nieuws/2026/02/23/dick-advocaat-stopt-als-bondscoach-curacao-om-gezondheidsproblemen-dochter-a4921243'],
       ['https://www.nrc.nl/nieuws/2026/02/23/ruslands-wegwerpsoldaten-zijn-na-vier-jaar-oorlog-in-oekraine-steeds-ouder-en-armer-a4920548'],
       ['https://www.nrc.nl/nieuws/2026/02/23/het-vonnis-is-geveld-anton-de-kom-moet-weg-a4921055']],
      dtype=object)

In [64]:
df[df['brand'] == 'www.nrc.nl']['first_10_chars'].value_counts()

first_10_chars
Als cadeau    2
Splinter C    1
Vrijdag he    1
‘Parttime’    1
Och, waren    1
             ..
Wat zijn d    1
Tegen de t    1
Een lange     1
Drie keer     1
Oké, je be    1
Name: count, Length: 96, dtype: int64

In [71]:
mask = (df['brand'] == 'nos.nl') & (df['word_count'] <2)
print(len(df[mask]))
df[mask][['news_uri']].values[0:5]

20

array([['https://nos.nl/artikel/2603689-koptelefoons-uit-voorzorg-uit-verkoop-na-onderzoek-schadelijke-stoffen?fbclid=IwZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAEeVAVW1qex22H407V7HMQSQnHSUDlUnO1pxdNW5GC39yVG0IbGlrCWGXfpHH0_aem_QSViykY_Q87byY2ye45OrQ'],
       ['https://nos.nl/artikel/2603749-pensioenaanbieders-zien-meer-interesse-van-zzp-ers-door-nieuwe-box-3-regels'],
       ['https://nos.nl/artikel/2603750-na-ex-prins-andrew-ook-britse-politicus-mandelson-opgepakt-in-epstein-zaak'],
       ['https://nos.nl/artikel/2603821-nieuwe-bbb-fractieleider-vermeer-vertrouwen-in-keijzer-echt-geknakt'],
       ['https://nos.nl/artikel/2603950-japan-gaat-raketten-plaatsen-op-eiland-in-buurt-taiwan?utm_medium=social&utm_source=bluesky']],
      dtype=object)

In [56]:
mask = (df['brand'] == 'www.volkskrant.nl') & (df['word_count'] <2)
df[mask][['news_uri']].values[0:5]

array([['https://www.volkskrant.nl/kijkverder/v/2025/de-wereld-in-beeld-de-opmerkelijkste-fotos-van-week-9-2026~v2743995/']],
      dtype=object)

In [ ]:
df[df['brand'] == 'www.volkskrant.nl']['first_10_chars'].value_counts()

first_10_chars
Gepublicee    2
De Amerika    2
Wat is er     2
Op een win    2
De tearoom    1
             ..
Wanneer is    1
De eerste     1
Harry Beer    1
Na een zor    1
Europa bev    1
Name: count, Length: 199, dtype: int64

In [57]:
df[(df['brand'] == 'www.rtl.nl') & (df['word_count'] <= 44)][['news_content']].value_counts()
mask = (df['brand'] == 'www.rtl.nl') & (df['word_count'] <= 44) & (df['news_content'].str.contains('Blijf op de hoogte van de nieuwste RTL'))
df[mask][['news_content']].values[0:5]

array([["Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw"],
       ["Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw"],
       ["Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw"],
       ["Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw"],
       ["Blijf op de hoogte van de nieuwste RTL programma's\n\nOntvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox\n\nJe bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.\n\nEr is iets misgegaan, probeer het opnieuw"]],
      dtype=object)

In [ ]:
df[df['brand'] == 'www.rtl.nl']['first_10_chars'].value_counts()

first_10_chars
Blijf op d    443
Dat blijkt      5
Het gaat o      4
Vanochtend      4
Het incide      3
             ...
1. Waarom       1
"Ik heb le      1
Het was va      1
Het bezoek      1
Harry en M      1
Name: count, Length: 419, dtype: int64

In [52]:
df[df['brand'] == 'www.nu.nl']['first_10_chars'].value_counts()

first_10_chars
Log in en     44
De Amerika     8
Op NU.nl v     7
Tallon Gri     5
Goedenavon     5
              ..
De coaliti     1
Xiaomi lan     1
Summer Yue     1
De eerste      1
De infecti     1
Name: count, Length: 489, dtype: int64

In [53]:
df[df['brand'] == 'www.ad.nl']['first_10_chars'].value_counts()

first_10_chars
‌\n\nmidden-    23
‌\n\nmet vid    21
analyse\n\nV    21
met video\n     19
Hoe is het      13
                ..
Na Bol.com       1
Smaaktest/       1
Zoveel pij       1
De voormal       1
09:30\n\nVoo     1
Name: count, Length: 420, dtype: int64

In [6]:
from blueskyranker.actor_annotator import ActorAnnotator
annotator = ActorAnnotator(model_name="gpt-oss:20b", seed=0, timeout=60)
print("Actor annotator initialized successfully!")

print("Testing with 100 articles first...")
test_df = data.sample(n=100, seed=76)

test_annotated = annotator.process_dataframe(
    df=test_df, 
    text_column='news_content', 
    title_column='news_title',
    id_column='uri'
)

Actor annotator initialized successfully!
Testing with 100 articles first...
Checking availability of model: gpt-oss:20b
Model gpt-oss:20b already available
Processing 100 articles...

Extracting actors:   1%|          | 1/100 [00:19<31:39, 19.18s/it]

Empty actors array found

Extracting actors:   3%|▎         | 3/100 [00:53<25:00, 15.47s/it]

Empty actors array found

Extracting actors:   5%|▌         | 5/100 [01:16<19:18, 12.19s/it]

Empty actors array found

Extracting actors:   6%|▌         | 6/100 [02:09<40:44, 26.01s/it]

No actors array pattern found in LLM response

Extracting actors:  10%|█         | 10/100 [02:41<18:38, 12.43s/it]

Empty actors array found

Extracting actors:  12%|█▏        | 12/100 [02:49<11:48,  8.05s/it]

Empty actors array found

Extracting actors:  14%|█▍        | 14/100 [03:07<11:23,  7.95s/it]

Empty actors array found

Extracting actors:  17%|█▋        | 17/100 [03:37<13:53, 10.05s/it]

Empty actors array found

Extracting actors:  23%|██▎       | 23/100 [04:39<12:04,  9.40s/it]

Empty actors array found

Extracting actors:  25%|██▌       | 25/100 [05:08<14:23, 11.52s/it]

Empty actors array found

Extracting actors:  26%|██▌       | 26/100 [05:12<11:17,  9.16s/it]

Empty actors array found

Extracting actors:  30%|███       | 30/100 [05:56<11:29,  9.84s/it]

Empty actors array found

Extracting actors:  33%|███▎      | 33/100 [06:26<10:59,  9.84s/it]

Empty actors array found

Extracting actors:  36%|███▌      | 36/100 [06:54<08:58,  8.41s/it]

Empty actors array found

Extracting actors:  42%|████▏     | 42/100 [07:41<05:30,  5.70s/it]

Empty actors array found

Extracting actors:  45%|████▌     | 45/100 [08:04<07:13,  7.88s/it]

Empty actors array found

Extracting actors:  46%|████▌     | 46/100 [08:17<08:23,  9.33s/it]

Request timed out after 60s - restarting client
Failed article has 1553 words
First 200 characters of content: LIVE VS | Regering VS beschuldigd van achterhouden Epstein-documenten over Trump
OpenAI heeft een akkoord bereikt met het Amerikaanse ministerie van Defensie voor het gebruik van AI-toepassingen binne
Ollama client recreated

Extracting actors:  47%|████▋     | 47/100 [11:17<53:32, 60.62s/it]

Retry after timeout also failed: timed out

Extracting actors:  48%|████▊     | 48/100 [11:20<37:33, 43.34s/it]

Empty actors array found

Extracting actors:  53%|█████▎    | 53/100 [12:06<11:16, 14.39s/it]

Empty actors array found

Extracting actors:  55%|█████▌    | 55/100 [12:20<07:56, 10.59s/it]

Empty actors array found

Extracting actors:  58%|█████▊    | 58/100 [13:28<12:05, 17.28s/it]

Empty actors array found

Extracting actors:  67%|██████▋   | 67/100 [15:58<05:38, 10.24s/it]

Empty actors array found

Extracting actors:  68%|██████▊   | 68/100 [16:00<04:13,  7.94s/it]

Empty actors array found

Extracting actors:  72%|███████▏  | 72/100 [16:27<02:46,  5.96s/it]

Empty actors array found

Extracting actors:  73%|███████▎  | 73/100 [16:29<02:06,  4.69s/it]

Empty actors array found

Extracting actors:  78%|███████▊  | 78/100 [18:56<09:30, 25.91s/it]

Empty actors array found

Extracting actors:  79%|███████▉  | 79/100 [18:59<06:40, 19.06s/it]

Empty actors array found

Extracting actors:  80%|████████  | 80/100 [19:01<04:41, 14.10s/it]

Empty actors array found

Extracting actors:  82%|████████▏ | 82/100 [19:18<03:24, 11.36s/it]

Request timed out after 60s - restarting client
Failed article has 794 words
First 200 characters of content: Echo’s van Lewinsky klinken door bij Epstein-verhoor van oud-president Clinton
Voor het eerst in de Amerikaanse geschiedenis werd een oud-president gedwongen te getuigen voor het Congres. Bill Clinton
Ollama client recreated

Extracting actors:  85%|████████▌ | 85/100 [21:06<05:09, 20.61s/it]

Empty actors array found

Extracting actors:  88%|████████▊ | 88/100 [22:31<04:32, 22.69s/it]

Empty actors array found

Extracting actors:  89%|████████▉ | 89/100 [22:44<03:40, 20.03s/it]

Empty actors array found

Extracting actors:  92%|█████████▏| 92/100 [23:12<01:38, 12.35s/it]

Empty actors array found
Request timed out after 60s - restarting client
Failed article has 1738 words
First 200 characters of content: GeenStijl: LIVEBLOG 6. Ayatollah Khamenei's interim-opvolger gekozen, 6 Israëlische doden door ballistische raket
De goeien hebben de extreme overhand, maar soms glipt er wel eens een banaan doorheen
Ollama client recreated

Extracting actors:  93%|█████████▎| 93/100 [26:12<07:18, 62.71s/it]

Retry after timeout also failed: timed out
Request timed out after 60s - restarting client
Failed article has 589 words
First 200 characters of content: Hongaars veto zet EU te kijk: Europese leiders met lege handen in Kyiv bij herdenking van Russische invasie
Het duo reist dinsdag naar de Oekraïense hoofdstad om het begin van de grote Russische invas
Ollama client recreated

Extracting actors: 100%|██████████| 100/100 [29:32<00:00, 17.73s/it]

Empty actors array found

In [11]:
test_annotated.head()

shape: (5, 4)
┌────────────────────────────────┬─────────────────────────┬────────────────┬──────────────────────┐
│ uri                            ┆ full_text               ┆ news_actors    ┆ raw_response         │
│ ---                            ┆ ---                     ┆ ---            ┆ ---                  │
│ str                            ┆ str                     ┆ str            ┆ str                  │
╞════════════════════════════════╪═════════════════════════╪════════════════╪══════════════════════╡
│ at://did:plc:toz4no26o2x4vsbum ┆ Video | Dapper hondje   ┆ ```json        ┆ null                 │
│ …                              ┆ jaagt in…               ┆ {              ┆                      │
│                                ┆                         ┆   "actors": [] ┆                      │
│                                ┆                         ┆ }              ┆                      │
│                                ┆                         ┆ ```            ┆                      │
│ at://did:plc:toz4no26o2x4vsbum ┆ Voor derde dag op rij   ┆ ```json        ┆ {"actors":           │
│ …                              ┆ demonstr…               ┆ {              ┆ [{"actor_name": "ee… │
│                                ┆                         ┆   "actors": [  ┆                      │
│                                ┆                         ┆     {          ┆                      │
│                                ┆                         ┆ …              ┆                      │
│ at://did:plc:toz4no26o2x4vsbum ┆ Schaatser Bosker grijpt ┆ ```json        ┆ null                 │
│ …                              ┆ macht …                 ┆ {              ┆                      │
│                                ┆                         ┆   "actors": [] ┆                      │
│                                ┆                         ┆ }              ┆                      │
│                                ┆                         ┆ ```            ┆                      │
│ at://did:plc:toz4no26o2x4vsbum ┆ Vereniging Eigen Huis   ┆ ```json        ┆ {"actors":           │
│ …                              ┆ heropent…               ┆ {              ┆ [{"actor_name": "Ve… │
│                                ┆                         ┆   "actors": [  ┆                      │
│                                ┆                         ┆     {          ┆                      │
│                                ┆                         ┆ …              ┆                      │
│ at://did:plc:toz4no26o2x4vsbum ┆ Oog in oog met het      ┆ ```json        ┆ null                 │
│ …                              ┆ waterkanon …            ┆ {              ┆                      │
│                                ┆                         ┆   "actors": [] ┆                      │
│                                ┆                         ┆ }              ┆                      │
│                                ┆                         ┆ ```            ┆                      │
└────────────────────────────────┴─────────────────────────┴────────────────┴──────────────────────┘

In [10]:
import pandas as pd
test_annotated_df = pd.DataFrame(test_annotated, columns=test_annotated.columns)
test_annotated_df.head()

,uri,full_text,news_actors,raw_response
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Video | Dapper hondje jaagt inbreker stuipen o...,"```json\n{\n ""actors"": []\n}\n```",None
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Voor derde dag op rij demonstraties bij univer...,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""een van de demonst..."
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Schaatser Bosker grijpt macht op NK allround\n...,"```json\n{\n ""actors"": []\n}\n```",None
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Vereniging Eigen Huis heropent meldpunt voor k...,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Vereniging Eigen H..."
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Oog in oog met het waterkanon – de tweede jeug...,"```json\n{\n ""actors"": []\n}\n```",None

In [12]:
# # write test_df for manual checks
import csv
# test_df.to_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/selected_articles_actorstesting3.csv', index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')
test_annotated_df.to_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/annotated_articles_actorstesting.csv', index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

In [13]:
import csv
import pandas as pd
test_annotated = pd.read_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/annotated_articles_actorstesting.csv', sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')
test_annotated.head()

,uri,full_text,news_actors,raw_response
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Video | Dapper hondje jaagt inbreker stuipen o...,"```json\n{\n ""actors"": []\n}\n```",NaN
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Voor derde dag op rij demonstraties bij univer...,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""een van de demonst..."
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Schaatser Bosker grijpt macht op NK allround\n...,"```json\n{\n ""actors"": []\n}\n```",NaN
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Vereniging Eigen Huis heropent meldpunt voor k...,"```json\n{\n ""actors"": [\n {\n ""actor...","{""actors"": [{""actor_name"": ""Vereniging Eigen H..."
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Oog in oog met het waterkanon – de tweede jeug...,"```json\n{\n ""actors"": []\n}\n```",NaN

In [15]:
test_annotated[test_annotated['raw_response'].isnull()].news_actors.value_counts(dropna=False)

news_actors
```json\n{\n  "actors": []\n}\n```                                                                                                                                                            31
NaN                                                                                                                                                                                            5
```json\n[\n  {\n    "actor": "Nicolò Barella",\n    "function": "b",\n    "party": null\n  },\n  {\n    "actor": "Christian Chivu",\n    "function": "b",\n    "party": null\n  }\n]\n```     1
Name: count, dtype: int64

In [19]:
print(test_annotated[test_annotated['raw_response'].isnull()].full_text.sample(5, random_state=76).values[0:5])

["LIVE eredivisie | Belangrijke kelderkraker tussen Excelsior en Go Ahead Eagles is onderweg\nExcelsiorEXC\neinde\n0\n1\nGo Ahead EaglesGAE\nSøren Tengstedt55'\neredivisie\nSøren Tengstedt helpt Go Ahead Eagles aan belangrijke zege op Excelsior\nGo Ahead Eagles heeft in de strijd om lijfsbehoud een belangrijke overwinning geboekt. Op Woudestein rekende de ploeg van Melvin Boel zondagavond met minimale cijfers af met degradatieconcurrent Excelsior (0-1) en neemt het weer afstand van de gevarenzone. Søren Tengstedt, de neef van Feyenoord-spits Casper, kroonde zich in Kralingen tot matchwinner.\nMichael Kerkhof\nExcelsior en Go Ahead Eagles mochten na een overvolle voetbalzondag voor het toetje zorgen. Een nagerecht om op voorhand op te verheugen, want er stond voor beide ploegen (allebei op 26 punten) écht iets op het spel.\nDoor de overwinning van FC Volendam en het gelijkspel van PEC Zwolle waren de uitslagen op zondag niet in het voordeel voor beide ploegen. Winst was noodzakelijk voor wat frisse lucht.\nExcelsior-trainer Ruben den Uil verwachtte een duel met hoge intensiteit. Hij en GAE-trainer Melvin Boel kennen elkaar al langer dan vandaag en delen een (cursus)verleden. Hoewel de eerste helft voor beide partijen wel wat kansen opleverde, bleef het echte spektakel uit. Mathis Suray zag aan GAE-kant een goal afgekeurd worden wegens buitenspel en Excelsior wist met onder andere Noah Naujoks - die tot drie doelpogingen kwam - ook niet toe te slaan.\nLees ook\nExcelsior moet weer naar beneden kijken na improductief avondje tegen Go Ahead Eagles\nNa rust zette Excelsior door en kreeg het met een kopbal van Ilias Bronkhorst en schot van Irakli Yegoian opnieuw twee goede mogelijkheden. Maar als je zelf niet scoort, dan doet de tegenstander dat wel. Na een actie van Richonell Margaret belandde de bal aan de andere kant van de zestien voor de voeten van Søren Tengstedt, waarna de neef van Feyenoord-spits Casper Tengstedt koeltjes raakschoot. Woudestein viel daarop compleet stil.\nExcelsior ging na de goal van Tengstedt op zoek naar de gelijkmaker. Met invaller Miliano Jonathans was het nog heel dichtbij, maar de aanvaller raakte de paal. In de rebound kon Lewis Schouten ook niet voor gevaar zorgen. Het moest bij de Kralingers van Mike van Duinen komen, de subersub die tegen FC Twente in het begin van het seizoen ook al in extremis voor belangrijke punten zorgde.\nMaar hoe goed Excelsior ook zocht, die goal viel niet. Zodoende pakte Go Ahead Eagles drie heel belangrijke punten en moet Excelsior serieus weer naar beneden kijken. Het gat met nummer 16 NAC Breda bedraagt immers nog maar vier punten.\nStand onderin de Eredivisie (na 25 duels)\n12. Go Ahead Eagles - 29 punten\n13. PEC Zwolle - 28 punten\n14. FC Volendam - 27 punten\n15. Excelsior Rotterdam - 26 punten\n16. NAC Breda - 22 punten\n17. Telstar - 21 punten\n18. Heracles Almelo - 17 punten\nliveblog\nBekijk alleen highlights\n90'+7'\nEinde tweede helft\n95'\nSchot van Wlodarczyk, maar De Busser redt.\n90'\nZes minuten blessuretijd. Valt de gelijkmaker nog?\n90'\nIrakli Yegoian wordt vervangen door Szymon Wlodarczyk\n89'\nRick Meissen wordt vervangen door Stan Henderikx\n86'\nVictor Edvardsen wordt vervangen door Evert Linthorst\n85'\nJulius Dirksen wordt vervangen door Dean James\n79'\nArthur Zagré wordt vervangen door Mike van Duinen\n78'\nGele kaart voor Arthur Zagré\n78'\nPaal!\nJonathans raakt de paal! In de drukte komt ook Schouten tot een schot, maar De Busser plukt de bal uit de lucht. Excelsior zet wel meer druk.\n76'\nRichonell Margaret wordt vervangen door Stefán Ingi Sigurdarson\n73'\nSchoten van Sanches Fernandes en Jonathans, maar twee keer zit er een verdediger tussen.\n71'\nMet Bergraaf en Jonathans vers binnen de lijnen valt Excelsior meteen aan. Naujoks krijgt een kopkans, maar mikt in de handen van De Busser.\n68'\nLennard Hartjes wordt vervangen door Jerolldino Bergraaf\n68'\nGyan de Regt wordt vervangen door Miliano Jonathans\n58'\nSøren Tengstedt wordt vervangen door Jaden Slory\n55'\n0-1 GOAL van Søren Tengstedt!\nWaar Excelsior de beste kansen krijgt, is Excelsior uiterst productief. Richonell Margaret houdt het overzicht en geeft de bal aan de man die aan de andere kant van de zestien vrij kan binnenschuiven: Tengstedt, al werd de bal nog van richting veranderd door Zagré. Een pijnlijke goal voor Excelsior, opluchting bij GAE.\n53'\nSchot van Yegoian\nNaujoks wordt weggestoken door Sanches Fernandes en krijgt de bal via een omweg bij Yegoian. Hij stuit op De Busser.\n47'\nHele mooi actie van Sanches Fernandes, die op het middenveld meerdere spelers uitspeelt. Daarna komt de bal na een voorzet op het hoofd van Bronkhorst, maar die lijkt te schrikken en knikt ver naast.\n46'\nJoris Kramer wordt vervangen door Giovanni van Zwam\nStand eredivisie\n\u200c\n\u200c\nLees ook\n• Programma eredivisie | Bekijk hier het speelschema\nLees meer\nMet video\nMatige tweede helft blijft zonder gevolgen voor koploper PSV op bezoek bij hekkensluiter Heracles\nMet video\nMatige tweede helft blijft zonder gevolgen voor koploper PSV op bezoek bij hekkensluiter Heracles\nOpvallende move: 29-jarige trainer moet Heracles behoeden voor degradatie\nOpvallende move: 29-jarige trainer moet Heracles behoeden voor degradatie\nPSV slaat slag en houdt groot Belgisch talent Noah Fernandez (18) binnenboord\nPSV slaat slag en houdt groot Belgisch talent Noah Fernandez (18) binnenboord\nmet video\nAZ naar achtste finales Conference League, Peer Koopmeiners imiteert geniale Oranje-assist van broer Teun\nmet video\nAZ naar achtste finales Conference League, Peer Koopmeiners imiteert geniale Oranje-assist van broer Teun"
 "Van roddelen tot eindeloze meetings: aan deze collega's ergeren Nederlanders zich het vaakst\nJe ziet ze soms meer dan je vrienden: je collega’s. Het is dan ook niet zo gek dat tweederde van de werkenden hun collega’s ziet als vrienden. Maar de werkvloer is óók een bron van frustratie. Uit onderzoek van Cvster onder 1325 Nederlanders blijkt dat vooral negativiteit de sfeer verpest.\nMaar wat is nu de grootste ergernis? Dat blijkt constant klagen te zijn.\nKlagende en roddelende collega’s het meest irritant\nBijna drie op de tien vrouwen noemen een negatieve houding of aanhoudend geklaag als hun grootste frustratie op het werk. Mannen lijken op dit punt iets toleranter, maar hebben weer minder geduld voor inefficiëntie. Ruim één op de zes mannen stoort zich vooral aan onnodig lange of zinloze meetings.\nEn roddelen? Dat staat bij zowel mannen als bij vrouwen in de top drie van irritaties. Dat geldt vooral bij jongeren tussen de 18 en 29 jaar. Zij noemen vooral het ‘roddelcircuit’ als grote ergernis. Dus dat roddelen bij de koffiehoek kun je misschien beter even achterwege laten.\nType werk en leeftijd speelt een rol\nHet type werk speelt een duidelijke rol in wat mensen stoort. Werknemers met een kantoorbaan ergeren zich het meest aan overbodige vergaderingen. Daarnaast blijkt lawaai een grote stoorzender: hard praten of luid bellen wordt op kantoor vier keer zo vaak als irritant ervaren.\nIn sectoren buiten kantoor, zoals de zorg of de bouw, liggen de frustraties anders. Daar storen werknemers zich vaker aan roddels en aan een rommelige werkplek.\nOok leeftijd maakt verschil. Naarmate werknemers ouder worden, groeit juist de frustratie over vergaderdruk. Onder zeventigplussers die nog werken, staat te veel vergaderen zelfs met stip op één.\nCollega’s toch ook vaak vrienden\nWel zagen de onderzoekers van Cvster dat, ondanks alle irritaties, de band tussen veel collega’s hecht is. Driekwart van de twintigers beschouwt één of meerdere collega’s als echte vrienden. Bij andere leeftijdsgroepen ligt dat percentage iets lager, maar nog altijd zegt ruim de helft van de werkenden met meerdere collega’s bevriend te zijn.\nVolgens Cvster is die onderlinge band cruciaal voor werkplezier. Uit eerder onderzoek van het platform bleek dat meer werkplezier voor ruim een kwart van de Nederlanders een belangrijke reden is om van baan te wisselen. Alleen een hoger salaris wordt nog vaker genoemd als motivatie om ander werk te zoeken.\nDit zijn de best gelezen artikelen van dit moment:\nDe Financiële fout van Ruud (47): ‘Kocht zonder advocaat een appartement in Spanje, maar er zat een schuld op het huis’\nWil heeft alzheimer, haar Hans (70) rijdt haar in een camper door heel Europa: ‘Dat is mijn plicht’\nVrouw twijfelt niet na hack bij Odido: ‘Nieuw abonnement, want ik ben al jaren klant’\nRenate (36) in Ex-treem gênant: ‘Hij wilde dat ik mijn kat voor hem weg zou doen’\nArianne (55) durft na scheiding Boer Zoekt Vrouw aan: ‘Een lekkere buitenman, beetje getekend’\nReacties"
 'Tallon Griekspoor boekt knappe zege op top 10-speler en gaat naar laatste acht in Dubai\nGriekspoor haalde vorig jaar de halve finale in Dubai waarin hij verloor van de Griek Stefanos Tsitsipas.\nHet jaar 2026 is tot dusver wisselvallig verlopen voor Griekspoor. Met name in de eerste weken was hij zonder een coach zoekende naar de juiste vorm. Begin deze maand won Griekspoor in het Franse Montpellier pas zijn eerste partij van het jaar; tegen de Spanjaard Pablo Carreno Busta. Sindsdien presteert Griekspoor beter. Tegen Boeblik behaalde hij zijn vijfde zege van dit seizoen.'
 "Video | Maker Ferry Doedens-documentaire: 'Laat iedereen er maar wat van vinden'\nLog in en lees reacties\nLees reacties, stel vragen aan de redactie, geef respect en praat mee over het belangrijkste nieuws."
 'Wat zegt een schilderijlijst? Donald Trump wil ze van goud, maar 17de-eeuwse Hollanders kozen juist zwart']

In [ ]:
for i in test_annotated.full_text.index:
    print("\nText:", test_annotated.full_text[i])
    print("Annotation Response:", test_annotated.raw_response[i])

Text: Video | Dapper hondje jaagt inbreker stuipen op het lijf in Brazilië
Log in en lees reacties
Lees reacties, stel vragen aan de redactie, geef respect en praat mee over het belangrijkste nieuws.
Annotation Response: nan

Text: Voor derde dag op rij demonstraties bij universiteiten in Iran
Voor de derde dag op rij zijn er demonstraties bij universiteiten in Iran. Met name in hoofdstad Teheran, maar ook in de stad Isfahan, op zo'n 400 kilometer ten zuiden van de hoofdstad, werd gedemonstreerd, meldt onder meer het Iraanse persbureau ILNA.
Bij de Amirkabir Technische Universiteit in Teheran gingen honderden studenten en medewerkers de straat op, is te zien op door BBC geverifieerde beelden. Ook op de prestigieuze Sharif Technische Universiteit in de hoofdstad werd gedemonstreerd, evenals op de Al-Azhar Universiteit, een onderwijsinstelling waar alleen vrouwen op zitten.
Het zijn de eerste grootschalige demonstraties op universiteiten sinds de demonstraties in december. Zaterdag gingen de universiteiten in het land voor het eerst sinds 4 januari weer open. De staat had die gesloten vanwege "extreme kou", maar volgens critici had het regime ze gesloten om te voorkomen dat er demonstraties plaats zouden vinden.
'Niet bang om te sterven'
Tijdens de demonstraties werden door studenten leuzen gescandeerd die gericht waren tegen het streng-islamitische regime. "We zijn niet bang om te sterven", zegt een van de demonstrerende studenten die The Guardian sprak. "We riskeren onze levens zodat de volgende generaties in dit land in vrijheid en vrede kunnen leven."
Hoewel het zaterdag voor het eerst was dat er weer studenten massaal de straat op gingen, gebeurde dat sinds afgelopen maand al vaker op kleine schaal , meldt The Guardian. Dat was vooral het geval bij medische studenten, die de vrijlating eisen van vastgezet medisch personeel. Een aantal dokters werd in de nasleep van de grootschalige demonstraties in januari opgepakt omdat zij gewonde demonstranten hadden geholpen.
Duizenden doden
Bij de eerdere demonstraties tegen het regime zijn volgens de Iraans-Amerikaanse mensenrechtenorganisatie HRANA meer dan 7000 mensen om het leven gekomen. De organisatie onderzoekt nog ruim tienduizend andere meldingen van doden en vreest daarom dat het daadwerkelijke dodental nog veel hoger ligt. Ook VN-experts denken dat het echte aantal veel hoger is en denken dat het om tienduizenden doden gaat.
De demonstraties in Iran begonnen 28 december in Teheran en verspreidden zich over het hele land. Aanvankelijk gingen mensen de straat op uit onvrede over de verslechterde economische situatie. Maar al snel riepen de demonstranten ook op tot het vertrek van het streng-islamitische regime.
Atoomakkoord
De spanningen in Iran en de landen eromheen zijn opgelopen sinds de VS dreigt Iran aan te gaan vallen als het niet akkoord gaat met de Amerikaanse voorwaarden voor een atoomakkoord. De VS heeft onder meer extra marineschepen en personeel naar het Midden-Oosten toegestuurd.
En vandaag haalde het land een groot deel van de Amerikaanse diplomaten in Libanon terug. In Libanon is de door Iran gesteunde Hezbollah-beweging actief. Mogelijk vreest de VS wraakacties van Hezbollah als het Iran aanvalt.
Annotation Response: {"actors": [{"actor_name": "een van de demonstrerende studenten", "actor_function": "d", "actor_pp": ""}, {"actor_name": "critici", "actor_function": "d", "actor_pp": ""}, {"actor_name": "Iraans-Amerikaanse mensenrechtenorganisatie HRANA", "actor_function": "c", "actor_pp": ""}, {"actor_name": "VN-experts", "actor_function": "b", "actor_pp": ""}, {"actor_name": "De VS", "actor_function": "a", "actor_pp": ""}, {"actor_name": "Hezbollah-beweging", "actor_function": "c", "actor_pp": ""}, {"actor_name": "demonstranten", "actor_function": "d", "actor_pp": ""}]}

Text: Schaatser Bosker grijpt macht op NK allround
Blijf op de hoogte van de nieuwste RTL programma's
Ontvang wekelijks updates over nieuwe programma's, exclusieve acties en persoonlijke tips in je mailbox
Je bent aangemeld. We hebben je een e-mail gestuurd om je inschrijving te bevestigen.
Er is iets misgegaan, probeer het opnieuw
Annotation Response: nan

Text: Vereniging Eigen Huis heropent meldpunt voor klachten over makelaars
Vereniging Eigen Huis (VEH) heropent een meldpunt voor klachten over makelaars. Dat loket werd vijf jaar geleden juist gesloten, maar is volgens de belangenvereniging nu opnieuw nodig omdat klachten en signalen over misstanden bij het kopen en verkopen van huizen blijven bestaan.
Aanleiding is onder meer onderzoek van consumentenprogramma Radar, waaruit blijkt dat veel kopers zich tijdens het biedproces onder druk gezet voelen.
Volgens VEH-directeur Cindy Kremer worden prijzen gemanipuleerd door makelaars omdat ze misbruik maken van hun informatievoorziening. Daarvan zouden zowel kopers als verkopers de dupe zijn. "Een verkoper kan worden benadeeld omdat de makelaar de woning gunt aan een koper van een bevriende relatie, waardoor niet iedereen de volle gelegenheid krijgt om de woning te bezichtigen en een bod te doen."
Daarnaast zegt ze dat de koper ook kan worden benadeeld als de makelaar zegt dat iemand het bod moet verhogen, terwijl je niet weet of dat echt zo is.
Makelaarsvereniging NVM laat aan de NOS weten zich maximaal in te spannen om misverstanden te voorkomen en het biedproces zo eerlijk mogelijk te laten verlopen. Dat gebeurt via een verplichte biedprocedure voor aangesloten makelaars, met een duidelijke uitleg voor consumenten. "Ook hebben we een onafhankelijke klachtenprocedure en tuchtrecht", aldus een woordvoerder.
'Zelfregulering werkt niet'
In de rondgang onder 2500 panelleden van Radar die de afgelopen vijf jaar een bod deden op een woning, gaf 43 procent van hen aan sturende informatie te hebben gekregen van een verkoopmakelaar. Bijna twee derde paste daarna het bod aan, meestal door meer te bieden of voorwaarden te laten vallen.
Ook ontvangt VEH zelf meldingen over onduidelijke regels en een gebrek aan transparantie. De zelfregulering waar de afgelopen jaren op werd ingezet, werkt volgens VEH niet.
Met het meldpunt wil VEH opnieuw actuele ervaringen verzamelen van kopers en verkopers. Zo moet zichtbaar worden dat structurele problemen nog altijd niet zijn opgelost.
Ook politiek wil verandering in biedproces
De NVM heeft een eigen biedprotocol met richtlijnen voor het verzamelen en verwerken van biedingen. Daarin wordt gewerkt met open inschrijving, waarbij biedingen niet openbaar zijn. Volgens Vereniging Eigen Huis blijft daardoor ruimte bestaan voor beïnvloeding en misbruik.
Ook in de politiek groeit de roep om verandering. De Tweede Kamer nam unaniem een motie aan waarin betrokken partijen worden opgeroepen om met een landelijk en transparant biedsysteem te komen. Als dat niet lukt, wil de politiek zelf met wetgeving komen.
Annotation Response: {"actors": [{"actor_name": "Vereniging Eigen Huis (VEH)", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Cindy Kremer", "actor_function": "c", "actor_pp": ""}, {"actor_name": "Makelaarsvereniging NVM", "actor_function": "c", "actor_pp": ""}, {"actor_name": "een woordvoerder", "actor_function": "c", "actor_pp": ""}, {"actor_name": "De Tweede Kamer", "actor_function": "a", "actor_pp": ""}]}

Text: Oog in oog met het waterkanon – de tweede jeugd van klimaatactivisten Toni en Jim
Annotation Response: nan

Text: Live Champions League | Club Brugge gaat voor stunt bij Atlético Madrid
Goedenavond en welkom in dit liveblog. Hier houd ik (Patrick Moeke) je op de hoogte van alle ontwikkelingen bij de wedstrijden in de Champions League. Veel plezier!
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media, marketing en personalisatie' cookies. Geef toestemming om deze inhoud te bekijken.
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media, marketing en personalisatie' cookies. Geef toestemming om deze inhoud te bekijken.
Uitslagen:
Atlético Madrid-Club Brugge 4-1
Newcastle-Qarabag 3-2
Liveblog
"Zo verliezen hoort bij het voetbal", zegt Nicolò Barella tegen Sky Sports. "Dat gebeurt. We moesten het eerste doelpunt maken, maar dat is ons niet gelukt. Gefeliciteerd aan Bodø/Glimt, zij hebben twee keer gewonnen en verdienden het om door te gaan. We zijn teleurgesteld. We willen in elke competitie zo ver mogelijk komen. We hebben het geprobeerd, maar zij waren beter dan wij."
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media' cookies. Geef toestemming om deze inhoud te bekijken.
Terwijl de Noren een feestje vieren op het veld in Milaan zijn ook de andere wedstrijden in Europa afgelopen. Bayer Leverkusen houdt Olympiacos op 0-0 en plaatst zich zo voor de laatste zestien. Ook Newcastle United gaat naar de achtste finales. Nadat het vorige week al met 1-6 won van Qarabag, eindigt de return mede door een doelpunt van Sven Botman in 3-2.
Afgelopen! Bodø/Glimt zorgt voor een van de grootste sensaties van de laatste jaren in de Champions League door verliezend finalist Internazionale uit te schakelen. De Noren winnen met 1-2 in Milaan, nadat het vorige wee thuis al 3-1 werd.
90' De bezoekers geloven het wel en lopen nu al massaal weg uit Stadio Giuseppe Meazza. En geef ze eens ongelijk, want deze wedstrijd is gespeeld. Er komen nog drie minuten blessuretijd bij.
86' Inter probeert het nog wel, maar de Noren blijven met hard werken overeind. Voor de duidelijkheid, Inter heeft dus nog drie goals nodig.
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media' cookies. Geef toestemming om deze inhoud te bekijken.
82' Daar is de rentree van Denzelf Dumfries. Na drie maanden blessureleed komt de Nederlander het veld in.
81' Een kopbal van Thuram uit een corner gaat over. Inter heeft nog minder dan tien minuten de tijd om drie goals te maken.
76' GOAL Internazionale! 1-2 (2-5)
Er moet doellijntechnologie aan te pas komen, maar hij zit er nu toch echt in. Bastoni maakt er met zijn knie 1-2 van. Doelman Haikin weet de bal weliswaar te vangen, maar doet dat net achter de lijn.
72' GOAL Bodø/Glimt! 0-2 (1-5)
Het gaat echt gebeuren! Wat een prachtige goal is dit van oud-AZ-speler Hakon Evjen. De aanvaller neemt de bal prachtig aan en schiet net zo mooi in de verre hoek. Dit moet de genadeklap zijn.
71' Het publiek begint te fluiten en de frustratie neemt toe. Het tempo ligt bij Inter veel te laag om de Noren vooralsnog serieus aan het wankelen te brengen
69' De paal voorkomt dat Akanji zijn fout van zojuist goed maakt. De verdediger zoekt de verre hoek, maar vindt het aluminium. Uit de rebound is de hoek voor Thuram te lastig om alsnog te scoren.
64' Leverkusen deelt bijna de genadeklap uit tegen Olympiacos. Grimaldo schiet vanuit een lastige hoek op de lat. Over twee wedstrijden staat het nog altijd 2-0.
61' Inter heeft nu dus drie (!) goals nodig en heeft daar ongeveer dertig minuten voor. Het lijkt een onmogelijke opgave.
58' GOAL Bodø/Glimt! 0-1 (1-4)
Het lijkt gedaan voor Inter! Verdediger Akanji levert de bal zomaar in en geeft een haast niet te missen kans aan Blomberg. Die schiet nog tegen Sommer op, waarna Hauge op de juiste plaats staat om uit de rebound 0-1 te maken. Inter balanceert op de rand van uitschakeling.
53' Frattesi geeft de bal met een stuit voor, maar Thuram kan er net niet bij. De frustratie begint zichtbaar toe te nemen bij de thuisploeg.
50' GOAL Qarabag! 2-1 (8-2)
Het is hier natuurlijk allang gespeeld, maar toch doet Qarabag nog wat terug. Camilo Durán mag alleen op het doel van de thuisploeg af en maakt er 2-1 van.
Rust! Internazionale krijgt genoeg mogelijkheden, maar komt nog niet door de stugge Noorse muur heen. De thuisploeg heeft minimaal twee goals nodig, maar heeft in de eerste 45 minuten niet gescoord: 0-0.
In Leverkusen verdedigt Bayer een 2-0-voorsprong tegen Olympiacos. De Grieken proberen het wel, maar de thuisploeg blijft vooralsnog eenvoudig overeind.
33' Aan de mogelijkheden ligt het niet. Ditmaal is het Zielinski die van afstand hard voorlangs schiet. Kan Inter scoren voor rust?
28' Frattesi lijkt uit een corner bij de eerste paal raak te koppen, maar doelman Haikin reageert meer dan goed. Het blijft 0-0 in Milaan.
25' Inter jaagt en jaagt, maar de bezoekers blijven nog altijd overeind. Een afgeslagen bal valt uiteindelijk voor de voeten van Dimarco, die in het zijnet schiet.
16' Een van richting veranderd schot van Thuram gaat maar net over. Inter dringt meer en meer aan.
12' Inter laat er geen gras over groeien en jaagt op het openingsdoelpunt. Het ontbreekt vooralsnog aan de juiste eindpass.
6' GOAL Newcastle! 2-0 (8-1)
Het zou wel eens een heel pijnlijk avond voor de Azeri's kunnen worden. Ditmaal staat Joelinton op de juiste plek bij de tweede paal om hard de 2-0 tegen de touwen te schieten.
5' GOAL Newcastle! 1-0 (7-1)
Hij ligt er alweer in Newcastle. Nadat het vorige week al 6-1 werd is het nu al Tonali met een snel doelpunt.
3' Daar is de eerste kans al voor Inter. Een kopbal van Esposito gaat maar net over.
1' Aftrap! De bal rolt bij Internazionale-Bodø/Glimt, Bayer Leverkusen-Olympiacos en Newcastle-Qarabag.
Na een flinke lichtshow komen de spelers het veld op in Stadio Giuseppe Meazza. Inmiddels draait het iconische stadion in Milaan weer volledig om voetbal.
Inter-trainer Christian Chivu wilde vorige week vooral de rust bewaren na het verrassende 3-1-verlies van zijn ploeg in Noorwegen. "Bodø is een erg sterke ploeg met veel kwaliteit en de ploeg is gewend om op dit veld te spelen. Waarschijnlijk veel meer dan wij, maar dat is geen excuus. Het team heeft de volle negentig minuten alles gegeven en een sterke mentaliteit getoond. Maar alles is nog mogelijk, want er is nog de returnwedstrijd. We weten dat zij een team hebben dat gevaarlijk kan zijn in de counter, maar we zullen tot het einde vechten en er alles aan doen om door te gaan."
Afgelopen! Atlético Madrid wint dankzij een hattrick van Sørloth met 4-1 van Club Brugge en is achtstefinalist.
90' Bijna nog 5-1. Uit de counter schiet Llorente maar net naast.
We werpen alvast een blik op de wedstrijden die later vanavond op het programma staan, waarbij Internazionale-Bodø/Glimt verreweg het interessantst is. De Noorse ploeg won vorige week verrassend met 3-1 van de verliezend finalist van vorig jaar. Bij Inter beginnen zowel Stefan de Vrij als Denzel Dumfries op de bank. Die laatste zit voor het eerst sinds drie maanden weer bij de selectie nadat hij hersteld is van een zware enkelblessure. Daarnaast staan ook nog Bayer Leverkusen-Olympiacos (2-0) en Newcastle-Qarabag (6-1) op het programma.
87' GOAL Atlético Madrid! 4-1
Een hattrick voor oud-FC Groningen-spits Alexander Sørloth! De aanvaller volleert van dichtbij binnen uit een perfecte voorzet van Ruggeri.
Ook vandaag heeft Brugge zich weer kranig geweerd, maar het lijkt niet genoeg te zijn. Atlético is nog een minuut of tien verwijderd van een plaats in de achtste finales van de Champions League.
76' GOAL Atlético Madrid! 3-1
En daar is de genadeklap voor Club Brugge. Het is Sørloth met zijn tweede. De Noor tikt van dichtbij binnen na goed voorbereidend werk van Griezmann en Lookman.
75' Kan Club Brugge zich nog een keertje oprichten? De energie lijkt er wel een beetje uit bij de nummer drie uit België.
70' Club Brugge schreeuwt om een penalty nadat Tzolis wordt gevloerd. De scheidsrechter wil er niks van weten en ook de VAR komt er niet op terug.
65' Een hard schot van Forbs wordt geblokt. Eindelijk weer wat gevaar van Club Brugge.
55' Atlético lijkt vleugels te hebben gekregen na de 2-1 en jaagt direct op nog een doelpunt. De bezoekers kunnen voor nu even alleen tegenhouden.
48' GOAL Atlético Madrid! 2-1
Boem, daar is al de 2-1 voor Atlético. Johnny Cardoso neemt de bal aan op de rand van het strafschopgebied. Hij twijfelt geen moment en knalt uit de stuit binnen in de rechterhoek. Brugge moet weer in de achtervolging.
Rust! Atlético en Club Brugge gaan even pauzeren. Dankzij de gehavende Ordóñez staat het halverwege 1-1.
43' Gevaarlijk schot van Sørloth die zijn harde poging maar net over de linker kruising ziet vliegen. We kijken naar een zeer vermakelijke eerste helft in Madrid.
38' Oblak redt Atlético. Met een uitstekende reflex voorkomt hij erger voor de thuisploeg nadat Vetlesen de bal voor het inkoppen heeft.
36' GOAL Club Brugge! 1-1
Daar is de gelijkmaker! En het is een opvallend doelpunt, want terwijl hij scoort kampt doelpuntenmaker Joel Ordóñez met een flinke bloedneus. Uit een corner die wordt doorgekopt kopt de verdediger van dichtbij binnen.
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media' cookies. Geef toestemming om deze inhoud te bekijken.
Bewegend beeld van de ketser van Mignolet.
30' En zo staat Atlético tegen de verhouding in op voorsprong. Maar vorige week stond Brugge op een 0-2-achterstand en toen kwamen de Belgen nog terug tot 3-3.
23' GOAL Atlético Madrid! 1-0 (4-3)
Een blundertje van doelman Mignolet! Het schot van Sørloth lijkt houdbaar, maar de bal stuitert ongelukkig over de Brugge-doelman heen.
Club Brugge heeft geen plankenkoorts in het eerste kwart van deze wedstrijd. De Belgen hebben het meeste balbezit en zoeken nadrukkelijk de aanval. Alleen een doelpunt ontbreekt er nog aan.
18' Hancko redt Atlético! De oud-Feyenoord kopt de bal van de lijn na een harde inzet van Vetlesen. De thuisploeg is gewaarschuwd.
13' Een gevaarlijke aanval belandt bij Koke, die de bal net naast tikt. Bij Atlético vinden ze dat Mignolet te stevig doorgaat en Koke naar de grond werkt, maar de scheidsrechter en ook de VAR willen daar niets van weten.
9' En daar is ook het eerste gevaar van Brugge. Een hard afstandsschot van Stankovic wordt klemvast gepakt door Oblak.
8' De eerste doelpoging is voor Atlético Madrid. Baena schiet uit de draai vanuit een lastige hoek over en naast.
5' Club Brugge begint agressief, heeft het meeste balbezit en houdt het tempo hoog. We wachten nog op de eerste kans van de wedstrijd.
1' Aftrap! De bezoekers brengen de wedstrijd op gang. We zijn onderweg bij Atlético Madrid-Club Brugge.
De Champions League-hymne klinkt en de spelers komen het veld op. De ruim zeventigduizend toeschouwers zijn er klaar voor.
In Nederland is het al even donker, maar boven het Riyadh Air Metropolitano schijnt nog een voorzichtig zonnetje. We gaan bijna beginnen in Madrid.
Oeps, dit kunnen we niet laten zien
Om deze inhoud te tonen, hebben we je toestemming nodig voor 'sociale media' cookies. Geef toestemming om deze inhoud te bekijken.
Bij Atlético staan onder anderen oud-Eredivisie-spelers David Hancko en Alexander Sørloth in de basis. Bij Club Brugge zien we oud-Ajacied Carlos Forbs aan de aftrap.
Atlético Madrid: Oblak; Llorente, Pubill, Hancko, Ruggeri; Giuliano Simeone, Koke, Cardoso, Baena; Álvarez, Sørloth.
Club Brugge: Mignolet; Sabbe, Ordóñez, Mechele, Seys; Stankovic, Vanaken, Vetlesen; Forbs, Tresoldi, Tzolis.
De enige Nederlander die vanavond kans maakt op speelminuten is Björn Meijer. De verdediger van Club Brugge begint op de bank.
Beeld: Getty Images
Aanbevolen artikelen
Annotation Response: nan

Text: Opinie | Madrid
Annotation Response: nan

Text: Sjoukje (44) in Opgebiecht: ‘Ik doe alsof ik druk ben met werk, maar lig vaak halve dagen op de bank’
Iedereen heeft weleens een geheim, een leugentje om bestwil, iets wat we liever niet hardop zeggen. In Metro’s rubriek Opgebiecht durft een Metro-lezer dat toch te doen. Deze week: Sjoukje (44) doet alsof ze heel druk is met haar werk, maar in werkelijkheid ligt ze soms halve dagen op de bank.

In [10]:
# Expand test results to actor-level
from blueskyranker.enrich_actors import ActorEnricher
enricher = ActorEnricher(
    actor_df=test_annotated,                              # Pass DataFrame directly (not path!)
    id_column='uri',                      # Your ID column name
    language='nl',                            # Language for NER
    center_parties=True,                      # Whether country has center parties
    save_politicians_df=False,                # Don't save _political.csv file
    political_data_path='politicians_NL.csv' # Path to reference data (optional)
)

Initializing Stanza NLP pipeline for language: nl
Loading party reference data from politicians_NL.csv

In [11]:
expanded_df, functions_df, enriched_political_df, ideology_df = enricher.run_full_enrichment(
    use_wikidata=True,  # Query Wikidata for missing party info
    language='nl'       # Language for Wikidata queries
)

============================================================
STARTING FULL ACTOR ENRICHMENT PIPELINE
============================================================

Step 1: Expanding actors to row-level...
Expanded to 264 actor records

Step 2: Calculating actor statistics per function...
Generated statistics for 64 articles

Step 3: Enriching political actors...
Processing 88 political actor records...
Extracting core names using NER...

Extracting names: 100%|██████████| 88/88 [00:01<00:00, 81.23it/s]

Extracted 88 valid person names
Matching against party reference data...
Step 2.1: Exact matching on core_actor_name...
  → Matched 6 actors with exact core_actor_name match
These names are matched with reference data: [{'core_actor_name': 'Eddy Van Hijum', 'matched_name': 'EDDY VAN HIJUM'}, {'core_actor_name': 'Jesse Klaver', 'matched_name': 'JESSE KLAVER'}, {'core_actor_name': 'Gouke Moes', 'matched_name': 'GOUKE MOES'}, {'core_actor_name': 'Mohammed Mohandis', 'matched_name': 'MOHAMMED MOHANDIS'}, {'core_actor_name': 'Henri Bontenbal', 'matched_name': 'HENRI BONTENBAL'}, {'core_actor_name': 'Dick Schoof', 'matched_name': 'DICK SCHOOF'}]
Step 2.2: Token matching on core_actor_name...
[SURNAME MATCH] DE HOOP → HABTAMU DE HOOP
[SURNAME MATCH] VAN OOSTEN → FOORT VAN OOSTEN
  → Matched 4 actors with token match on core_actor_name
These names are matched with reference data: [{'core_actor_name': 'Eddy Van Hijum', 'matched_name': 'EDDY VAN HIJUM'}, {'core_actor_name': 'De Hoop', 'matched_name': 'HABTAMU DE HOOP'}, {'core_actor_name': 'Jesse Klaver', 'matched_name': 'JESSE KLAVER'}, {'core_actor_name': 'Gouke Moes', 'matched_name': 'GOUKE MOES'}, {'core_actor_name': 'Mohammed Mohandis', 'matched_name': 'MOHAMMED MOHANDIS'}, {'core_actor_name': 'Henri Bontenbal', 'matched_name': 'HENRI BONTENBAL'}, {'core_actor_name': 'Schoof', 'matched_name': 'DICK SCHOOF'}, {'core_actor_name': 'Dick Schoof', 'matched_name': 'DICK SCHOOF'}, {'core_actor_name': 'Van Oosten', 'matched_name': 'FOORT VAN OOSTEN'}, {'core_actor_name': 'Kamerlid Straatman', 'matched_name': 'JELTJE STRAATMAN'}]
Step 2.3: Matching on original actor_name...
  → Matched 0 actors with actor_name matching
Step 2.4: Checking for party name mentions...
. → Matched 5 actors with party name mentions

Total matched: 17 actors with reference data
Querying Wikidata for 73 actors with missing party info...
Querying 42 unique names...

Wikidata queries: 100%|██████████| 42/42 [00:34<00:00,  1.23it/s]

Updating party reference data with Wikidata results...
Enriched 21 political actor records

Step 4: Calculating actors per party ideology...
Generated ideology statistics for 8 articles

============================================================
ENRICHMENT PIPELINE COMPLETED
============================================================

In [12]:
expanded_df.head()

,uri,actor_name,actor_function,actor_pp,news_actors_raw
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Cate Blanchett,b,,
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,

In [13]:
expanded_df.actor_function.value_counts()

actor_function
a    88
b    76
     63
d    27
c    10
Name: count, dtype: int64

In [ ]:
functions_df.head()

actor_function,uri,nr_actors_a,nr_actors_b,nr_actors_c,nr_actors_d,nr_actors_total
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,2.0,0.0,3.0,6.0
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,0.0,0.0,1.0,1.0
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,3.0,0.0,0.0,1.0,4.0
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,2.0,0.0,0.0,0.0,2.0
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,0.0,0.0,0.0,1.0

In [22]:
print("Actor functions in functions_df:")
print(functions_df.nr_actors_a.sum())
print(functions_df.nr_actors_b.sum())
print(functions_df.nr_actors_c.sum())
print(functions_df.nr_actors_d.sum())

Actor functions in functions_df:
88.0
76.0
10.0
27.0

In [18]:
enriched_political_df.head()

,uri,actor_name,actor_function,actor_pp,news_actors_raw,core_actor_name,core_actor_name_upper,actor_name_upper,party,lrgen_category,matched_name
8,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Dirk Gotink,a,,,Dirk Gotink,DIRK GOTINK,DIRK GOTINK,CDA,center,NaN
9,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Eddy van Hijum,a,,,Eddy Van Hijum,EDDY VAN HIJUM,EDDY VAN HIJUM,NSC,right,EDDY VAN HIJUM
10,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,De Hoop (GroenLinks-PvdA),a,GroenLinks-PvdA,,De Hoop,DE HOOP,DE HOOP (GROENLINKS-PVDA),GL-PvdA,left,HABTAMU DE HOOP
16,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Dirk Gotink,a,NSC,,Dirk Gotink,DIRK GOTINK,DIRK GOTINK,CDA,center,NaN
20,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Jesse Klaver,a,GroenLinks-PvdA,,Jesse Klaver,JESSE KLAVER,JESSE KLAVER,GL-PvdA,left,JESSE KLAVER

In [20]:
enriched_political_df.lrgen_category.value_counts(dropna=False)

lrgen_category
right      8
center     6
left       5
unknown    2
Name: count, dtype: int64

In [21]:
ideology_df.head()

lrgen_category,uri,nr_actors_center,nr_actors_left,nr_actors_right,nr_actors_total
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,1.0,0.0,1.0
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,0.0,1.0,2.0
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,0.0,1.0,1.0
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,1.0,1.0,3.0
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,0.0,1.0,1.0

In [24]:
print("Actor parties in ideology_df:")
print("left:", ideology_df.nr_actors_left.sum())
print("right:", ideology_df.nr_actors_right.sum())
print("center:", ideology_df.nr_actors_center.sum())

Actor parties in ideology_df:
left: 5.0
right: 8.0
center: 6.0

In [24]:
test_actors_function.to_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/functions_actors_actorstesting.csv', index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

In [16]:
test_actors_df['core_actor_name'] = test_actors_df['actor_name'].apply(enricher.extract_core_name)

In [17]:
test_actors_df.head()

,uri,actor_name,actor_function,actor_pp,news_actors_raw,core_actor_name
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Cate Blanchett,b,,,Cate Blanchett
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,,None
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,,None
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,,None
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,,,,,None

In [18]:
# read the political actors df 
import csv
party_reference_df = pd.read_csv('politicians_NL.csv', sep=';', quoting=csv.QUOTE_NONNUMERIC)
party_reference_df['name'] = party_reference_df['name'].str.title().str.strip()

party_reference_df.head()

                name    party       chamber     lrgen lrgen_category
0     Alexander Kops      PVV  Tweede Kamer  9.083333          right
1        André Flach      SGP  Tweede Kamer  8.000000          right
2       Ani Zalinyan  GL-PvdA  Tweede Kamer  2.766667           left
3   Annabel Nanninga     JA21  Tweede Kamer  9.833333          right
4  Anne-Marijke Podt      D66  Tweede Kamer  4.666666         center

In [19]:
pol_df = enricher.enrich_political_actors(test_actors_df, use_wikidata=True, language='nl')

Processing 88 political actor records...
Extracting core names using NER...

Extracting names: 100%|██████████| 88/88 [00:01<00:00, 80.41it/s]

Extracted 88 valid person names
Matching against party reference data...
Step 2.1: Exact matching on core_actor_name...
  → Matched 6 actors with exact core_actor_name match
These names are matched with reference data: [{'core_actor_name': 'Eddy Van Hijum', 'matched_name': 'EDDY VAN HIJUM'}, {'core_actor_name': 'Jesse Klaver', 'matched_name': 'JESSE KLAVER'}, {'core_actor_name': 'Gouke Moes', 'matched_name': 'GOUKE MOES'}, {'core_actor_name': 'Mohammed Mohandis', 'matched_name': 'MOHAMMED MOHANDIS'}, {'core_actor_name': 'Henri Bontenbal', 'matched_name': 'HENRI BONTENBAL'}, {'core_actor_name': 'Dick Schoof', 'matched_name': 'DICK SCHOOF'}]
Step 2.2: Token matching on core_actor_name...
[SURNAME MATCH] DE HOOP → HABTAMU DE HOOP
[SURNAME MATCH] VAN OOSTEN → FOORT VAN OOSTEN
  → Matched 4 actors with token match on core_actor_name
These names are matched with reference data: [{'core_actor_name': 'Eddy Van Hijum', 'matched_name': 'EDDY VAN HIJUM'}, {'core_actor_name': 'De Hoop', 'matched_name': 'HABTAMU DE HOOP'}, {'core_actor_name': 'Jesse Klaver', 'matched_name': 'JESSE KLAVER'}, {'core_actor_name': 'Gouke Moes', 'matched_name': 'GOUKE MOES'}, {'core_actor_name': 'Mohammed Mohandis', 'matched_name': 'MOHAMMED MOHANDIS'}, {'core_actor_name': 'Henri Bontenbal', 'matched_name': 'HENRI BONTENBAL'}, {'core_actor_name': 'Schoof', 'matched_name': 'DICK SCHOOF'}, {'core_actor_name': 'Dick Schoof', 'matched_name': 'DICK SCHOOF'}, {'core_actor_name': 'Van Oosten', 'matched_name': 'FOORT VAN OOSTEN'}, {'core_actor_name': 'Kamerlid Straatman', 'matched_name': 'JELTJE STRAATMAN'}]
Step 2.3: Matching on original actor_name...
  → Matched 0 actors with actor_name matching
Step 2.4: Checking for party name mentions...
. → Matched 5 actors with party name mentions

Total matched: 17 actors with reference data
Querying Wikidata for 73 actors with missing party info...
Querying 44 unique names...

Wikidata queries: 100%|██████████| 44/44 [00:27<00:00,  1.61it/s]

Updating party reference data with Wikidata results...

In [20]:
print(pol_df.shape)

pol_df.sort_values(by=['actor_name'])[['uri', 'actor_name', 'actor_function', 'core_actor_name', 'matched_name', 'party']]

(20, 11)

,uri,actor_name,actor_function,core_actor_name,matched_name,party
89,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,D66 en VVD,a,None,VVD,VVD
77,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,D66 en VVD,a,None,D66,D66
10,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,De Hoop (GroenLinks-PvdA),a,De Hoop,HABTAMU DE HOOP,GL-PvdA
68,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Demissionair minister Van Oosten (VVD),a,Van Oosten,FOORT VAN OOSTEN,VVD
65,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Dick Schoof,a,Dick Schoof,DICK SCHOOF,partijloos
8,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Dirk Gotink,a,Dirk Gotink,NaN,CDA
16,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Dirk Gotink,a,Dirk Gotink,NaN,CDA
9,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Eddy van Hijum,a,Eddy Van Hijum,EDDY VAN HIJUM,NSC
37,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Gouke Moes,a,Gouke Moes,GOUKE MOES,BBB
69,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,GroenLinks-PvdA-politica Mutluer,a,Groenlinks-Pvda-Politica Mutluer,GROENLINKS-PVDA,GROENLINKS-PVDA
39,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Henri Bontenbal,a,Henri Bontenbal,HENRI BONTENBAL,CDA
75,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,JA21-Kamerlid Coenradie,a,Ja21-Kamerlid Coenradie,JA21,JA21
20,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Jesse Klaver,a,Jesse Klaver,JESSE KLAVER,GL-PvdA
76,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Kamerlid Straatman,a,Kamerlid Straatman,JELTJE STRAATMAN,CDA
35,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Mark Rutte,a,Mark Rutte,NaN,VVD
38,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Mohammed Mohandis,a,Mohammed Mohandis,MOHAMMED MOHANDIS,GL-PvdA
41,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,Premier Schoof,a,Schoof,DICK SCHOOF,partijloos
88,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,SP en D66,a,None,SP,SP
74,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,SP en D66,a,None,D66,D66
73,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,VVD-Kamerlid Michon,a,Kamerlid Michon,VVD,VVD

In [23]:
ideology_df = enricher.calculate_actors_per_partyideology(pol_df, center_parties=True)
ideology_df.head()

lrgen_category,uri,nr_actors_center,nr_actors_left,nr_actors_right,nr_actors_total
0,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,1.0,0.0,1.0
1,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,0.0,1.0,2.0
2,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,0.0,0.0,1.0,1.0
3,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,1.0,1.0,1.0,3.0
4,at://did:plc:toz4no26o2x4vsbum7cp4bxp/app.bsky...,3.0,2.0,4.0,9.0

In [25]:
# lets write pol_df to csv for manual checks
pol_df.to_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/political_actors_actorstesting.csv', index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

In [26]:
pol_df.lrgen_category.value_counts(dropna=False)

lrgen_category
right      7
center     6
left       5
unknown    2
Name: count, dtype: int64

In [28]:
print(ideology_df.nr_actors_center.sum())
print(ideology_df.nr_actors_left.sum())
print(ideology_df.nr_actors_right.sum())

6.0
5.0
7.0

In [29]:
ideology_df.to_csv('/home/eklk/data/storage100gb5/blueskyranker/tests/ideology_actors_actorstesting.csv', index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

In [ ]:
df['domain'] = df[16].map(lambda x: " ".join(x.replace("www.","").split('.')[:1]))
df['isempty'] = df[15].isnull()
pd.crosstab(df['domain'], df['isempty']).sort_values(by=True, ascending=False).head(20)

In [ ]:
# read example.csv
example_df = pd.read_csv("blueskyranker/example_news.csv")
print(example_df.shape)
example_df.head()

In [ ]:
# print news_uri, news_description and text
example_df[['news_uri', 'news_description', 'text']].values[1]

## 3) Rank posts by topic

- Methods: `networkclustering-tfidf`, `networkclustering-count`, `networkclustering-sbert` (slower, higher semantic quality).
- `similarity_threshold`: raise for fewer/tighter clusters.
- `vectorizer_stopwords`: 'english' | list of words | None.

In [ ]:
ranker = TopicRanker(
    returnformat='dataframe',
    method='networkclustering-sbert',  # try 'networkclustering-tfidf' for semantics
    descending=True,
    similarity_threshold=0.2,
    vectorizer_stopwords='english',
    # Optional windows (days):
    cluster_window_days=7,
    engagement_window_days=3,
    push_window_days=1,
)
ranking = ranker.rank(data)
ranking.head()

## 4) Inspect top clusters and posts

- We show the 3 most engaged clusters.
- For each, we list the 5 most recent posts with key fields.

In [ ]:
clusters = (
    ranking.group_by('cluster')
    .agg([
        pl.col('cluster_size').first().alias('size'),
        pl.col('cluster_engagement_count').first().alias('engagement')
    ])
    .sort('engagement', descending=True)
    .head(3)
)
for row in clusters.iter_rows(named=True):
    cid = row['cluster']
    size = int(row['size']) if row['size'] is not None else 0
    eng = int(row['engagement']) if row['engagement'] is not None else 0
    print(f"\n=== Cluster {cid} | size={size} | engagement={eng}")
    subset = (
        ranking.filter(pl.col('cluster') == cid)
        .sort('createdAt', descending=True)
        .head(5)
    )
    for rec in subset.select(['uri','text','news_title','news_description','news_uri']).iter_rows(named=True):
        print(f"- uri: {rec['uri']}")
        print(f"  text: {rec.get('text')}")
        print(f"  news_title: {rec.get('news_title')}")
        print(f"  news_description: {rec.get('news_description')}")
        print(f"  news_uri: {rec.get('news_uri')}")

## 5) (Optional) Generate a cluster report

- This writes `cluster_report.md` with top clusters per handle.
- You can adjust method, threshold, and stopwords.

## 6) (Optional) End-to-end: fetch → rank → push (per handle)

- Runs the whole flow and logs a short cluster summary to `push.log`.

In [ ]:
from blueskyranker.pipeline import run_fetch_rank_push
run_fetch_rank_push(
    handles=[handle],
    method='networkclustering-sbert', similarity_threshold=0.5,
    cluster_window_days=7, engagement_window_days=1, push_window_days=1,
    include_pins=False, test=True, log_path='push.log'
)

In [ ]:
from blueskyranker.cluster_report import generate_cluster_report
generate_cluster_report(db_path='newsflows.db', output_path='cluster_report.md',
                        method='networkclustering-sbert', sample_max=300,
                        similarity_threshold=0.2, vectorizer_stopwords='english')
print('Wrote cluster_report.md')

### Pipeline updates (priority and demotion)

- Priority assignment now starts at 1000 for the first item and decreases by 1 (1000, 999, 998, …). The minimum is clamped at 1. Items explicitly demoted are sent with priority 0.
- Demotion: by default, all posts from the last 48 hours that are not in the current prioritisation are sent with priority 0. Configure via `--demote-window-hours`.
- Export filenames use a human‑readable UTC timestamp: `push_{handle}_{YYYY-MM-DDTHH-mm-ssZ}.json`.
- Server responses: short responses print to stdout; long responses are saved to `push_exports/prioritize_response_{handle}_{YYYY-MM-DDTHH-mm-ssZ}.{json|txt}`.

Example CLI:

```
python -m blueskyranker.pipeline \
+  --handles news-flows-nl.bsky.social news-flows-fr.bsky.social \
+  --method networkclustering-tfidf \
+  --similarity-threshold 0.2 \
+  --cluster-window-days 7 \
+  --engagement-window-days 1 \
+  --push-window-days 2 \
+  --demote-last \
+  --demote-window-hours 48 \
+  --log-path push.log \
+  --no-test
```

Programmatic call:

```python
from blueskyranker.pipeline import run_fetch_rank_push
run_fetch_rank_push(
    handles=['news-flows-nl.bsky.social'],
    method='networkclustering-tfidf', similarity_threshold=0.2,
    cluster_window_days=7, engagement_window_days=1, push_window_days=2,
    demote_last=True, demote_window_hours=48,
    include_pins=False, test=True, log_path='push.log')
```

### Pipeline updates (priority and demotion)

- Priority assignment now starts at 1000 for the first item and decreases by 1 (1000, 999, 998, …). The minimum is clamped at 1. Items explicitly demoted are sent with priority 0.
- Demotion: by default, all posts from the last 48 hours that are not in the current prioritisation are sent with priority 0. Configure via `--demote-window-hours`.
- Export filenames use a human‑readable UTC timestamp: `push_{handle}_{YYYY-MM-DDTHH-mm-ssZ}.json`.
- Server responses: short responses print to stdout; long responses are saved to `push_exports/prioritize_response_{handle}_{YYYY-MM-DDTHH-mm-ssZ}.{json|txt}`.

Example CLI:

```
python -m blueskyranker.pipeline \
+  --handles news-flows-nl.bsky.social news-flows-fr.bsky.social \
+  --method networkclustering-tfidf \
+  --similarity-threshold 0.2 \
+  --cluster-window-days 7 \
+  --engagement-window-days 1 \
+  --push-window-days 2 \
+  --demote-last \
+  --demote-window-hours 48 \
+  --log-path push.log \
+  --no-test
```

Programmatic call:

```python
from blueskyranker.pipeline import run_fetch_rank_push
run_fetch_rank_push(
    handles=['news-flows-nl.bsky.social'],
    method='networkclustering-tfidf', similarity_threshold=0.2,
    cluster_window_days=7, engagement_window_days=1, push_window_days=2,
    demote_last=True, demote_window_hours=48,
    include_pins=False, test=True, log_path='push.log')
```

### Ordering logic (time windows)

- Clustering window: clusters are built from posts in this window (e.g., 7 days).
- Engagement window: cluster engagement is computed here to derive `cluster_engagement_rank` (1 = most engaged).
- Push window: only posts in this window are eligible for the final feed.

Order of posts:

1) Filter to the push window.

2) Order clusters by engagement rank (most engaged first).

3) Within each cluster, sort by recency (newest first).

4) Interleave round‑robin across clusters in rank order (1, 2, 3, … then repeat).

Result: the first post is the most‑recent item from the most‑engaged cluster that has posts in the push window.